import React,{useEffect,useMemo,useState}from'react';
import'./battle-fixed.css';
const API='https://pokeapi.co/api/v2';
const STORE='pokemon-jdr-battle-v4';
const TYPES={normal:'NORMAL',fire:'FEU',water:'EAU',electric:'ÉLECTRIK',grass:'PLANTE',ice:'GLACE',fighting:'COMBAT',poison:'POISON',ground:'SOL',flying:'VOL',psychic:'PSY',bug:'INSECTE',rock:'ROCHE',ghost:'SPECTRE',dragon:'DRAGON',dark:'TÉNÈBRES',steel:'ACIER',fairy:'FÉE'};
const ITEMS=['Potion','Super Potion','Hyper Potion','Potion Max','Rappel','Rappel Max','Antidote','Anti-Para','Anti-Brûle','Anti-Gel','Réveil','Total Soin','Baie Sitrus','Orbe Vie'];
const FALLBACK={1:'Bulbizarre',4:'Salamèche',7:'Carapuce',25:'Pikachu',133:'Évoli',150:'Mewtwo'};
const title=s=>String(s||'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' '),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
async function get(u){const r=await fetch(u);if(!r.ok)throw Error(r.status);return r.json()}
const cache=new Map();
async function moveData(url){if(cache.has(url))return cache.get(url);const p=get(url).then(x=>({id:x.id,name:x.names?.find(n=>n.language?.name==='fr')?.name||title(x.name),type:x.type?.name||'normal',power:x.power||0,accuracy:x.accuracy||100,pp:x.pp||1,maxPP:x.pp||1,damageClass:x.damage_class?.name||'status',effect:x.effect_entries?.find(e=>e.language?.name==='fr')?.short_effect||x.effect_entries?.find(e=>e.language?.name==='en')?.short_effect||'Aucun effet.'})).catch(()=>null);cache.set(url,p);return p}
async function hydrate(ref){const d=await get(ref.url||`${API}/pokemon/${ref.id}`),level=clamp(Number(ref.level)||50,1,100),types=(d.types||[]).sort((a,b)=>a.slot-b.slot).map(x=>x.type.name),stats={};for(const s of d.stats||[])stats[s.stat.name.replace('special-attack','specialAttack').replace('special-defense','specialDefense')]=s.base_stat;const learned=d.moves.flatMap(m=>(m.version_group_details||[]).filter(v=>['heartgold-soulsilver','sword-shield','scarlet-violet'].includes(v.version_group.name)&&v.move_learn_method.name==='level-up'&&v.level_learned_at<=level).map(v=>({url:m.move.url,level:v.level_learned_at})));const uniq=[];for(const m of learned)if(!uniq.some(x=>x.url===m.url))uniq.push(m);const details=(await Promise.all(uniq.map(moveData))).filter(Boolean),pool=details.filter(m=>m.power>0).length>=4?details.filter(m=>m.power>0):details;const moves=pool.sort((a,b)=>(b.power*(b.accuracy/100)+(types.includes(b.type)?25:0))-(a.power*(a.accuracy/100)+(types.includes(a.type)?25:0))).slice(0,4);const hp=Math.floor((2*(stats.hp||50)*level)/100)+level+10;return{...ref,id:d.id,name:d.names?.find(n=>n.language?.name==='fr')?.name||title(d.name),level,hp,maxHp:hp,baseMaxHp:hp,stats,types,moves:moves.length?moves:[{id:33,name:'Charge',type:'normal',power:40,accuracy:100,pp:35,maxPP:35,damageClass:'physical',effect:'Inflige des dégâts.'}],spriteId:d.id,mega:false,dynamax:false,tera:false,teraType:types[0]||'normal'}}
const sprite=(p,back=false)=>`https://cdn.jsdelivr.net/gh/PokeAPI/sprites@master/sprites/versions/generation-iv/heartgold-soulsilver/${back?'back/':''}${p.spriteId||p.id}.png`;
function useStore(){const[db,setDb]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORE))||{slots:[[],[]],items:Object.fromEntries(ITEMS.map(x=>[x,3]))}}catch{return{slots:[[],[]],items:Object.fromEntries(ITEMS.map(x=>[x,3]))}}});useEffect(()=>localStorage.setItem(STORE,JSON.stringify(db)),[db]);return[db,setDb]}
function Picker({team,setTeam}){const[q,setQ]=useState(''),[list,setList]=useState([]);useEffect(()=>{get(`${API}/pokemon?limit=1025`).then(d=>setList(d.results.map((x,i)=>({id:i+1,name:title(x.name),url:x.url})))).catch(()=>{})},[]);const shown=useMemo(()=>{const s=q.toLowerCase().trim();return s?list.filter(x=>String(x.id).includes(s)||x.name.toLowerCase().includes(s)):list},[list,q]);return <div className="pb-picker"><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Rechercher un Pokémon / numéro"/><div className="pb-grid">{shown.slice(0,120).map(p=><button key={p.id}disabled={team.length>=6||team.some(x=>x.id===p.id)}onClick={()=>setTeam([...team,{...p,level:50,item:'Aucun'}])}><img src={sprite(p)}/><b>#{p.id}</b><span>{p.name}</span></button>)}</div></div>}
function TeamEditor({label,team,setTeam,onSave}){const[open,setOpen]=useState(false);return <section className="pb-card"><header><b>{label}</b><span>{team.length}/6</span></header>{team.map((p,i)=><div className="pb-member"key={i}><img src={sprite(p)}/><div><b>{p.name}</b><label>Nv <input type="number"min="1"max="100"value={p.level||50}onChange={e=>setTeam(team.map((x,j)=>j===i?{...x,level:clamp(+e.target.value||1,1,100)}:x))}/></label><label>Objet <select value={p.item||'Aucun'}onChange={e=>setTeam(team.map((x,j)=>j===i?{...x,item:e.target.value}:x))}><option>Aucun</option>{ITEMS.map(x=><option key={x}>{x}</option>)}</select></label></div><button onClick={()=>setTeam(team.filter((_,j)=>j!==i))}>×</button></div>)}<button className="pb-add"disabled={team.length>=6}onClick={()=>setOpen(!open)}>+ AJOUTER UN POKÉMON</button>{open&&<Picker team={team}setTeam={setTeam}/>}<button className="pb-save"onClick={onSave}>SAUVEGARDER L'ÉQUIPE</button></section>}
function Setup({onExit,onStart,gm=false}){const[db,setDb]=useStore(),[a,setA]=useState(db.slots[0]||[]),[b,setB]=useState(db.slots[1]||[]),[slot,setSlot]=useState(0),[loading,setLoading]=useState(false),[saved,setSaved]=useState('');const save=(n,t)=>{setDb(d=>({...d,slots:d.slots.map((x,i)=>i===n?t:x)}));setSaved(`Équipe ${n+1} sauvegardée.`);setTimeout(()=>setSaved(''),1800)};const load=n=>{setSlot(n);if(n===0)setA(db.slots[0]||[]);else setB(db.slots[1]||[])};const start=async()=>{if(!a.length||!b.length)return;setLoading(true);try{onStart(await Promise.all(a.map(hydrate)),await Promise.all(b.map(hydrate)),db.items)}finally{setLoading(false)}};return <div className="pb-screen"><header className="pb-head"><button onClick={onExit}>← QUITTER</button><div><b>{gm?'COMBAT MJ':'COMBAT POKÉMON'}</b><small>Équipes, objets et données conservés dans le navigateur</small></div><span>SAUVEGARDE LOCALE</span></header><main className="pb-setup"><div className="pb-slots"><button className={slot===0?'sel':''}onClick={()=>load(0)}>ÉQUIPE JOUEUR</button><button className={slot===1?'sel':''}onClick={()=>load(1)}>ÉQUIPE ADVERSAIRE</button></div><div className="pb-cols"><TeamEditor label="ÉQUIPE JOUEUR" team={a}setTeam={setA}onSave={()=>save(0,a)}/><TeamEditor label="ÉQUIPE ADVERSAIRE" team={b}setTeam={setB}onSave={()=>save(1,b)}/><section className="pb-card pb-bag"><header><b>SAC / OBJETS</b><span>{Object.values(db.items).reduce((a,b)=>a+b,0)}</span></header>{ITEMS.map(x=><div key={x}><b>{x}</b><input type="number"min="0"value={db.items[x]||0}onChange={e=>setDb(d=>({...d,items:{...d.items,[x]:Math.max(0,+e.target.value||0)}}))}/></div>)}<p>Les objets et les deux équipes sont persistants après actualisation.</p></section></div>{saved&&<div className="pb-toast">{saved}</div>}<button className="pb-launch"disabled={!a.length||!b.length||loading}onClick={start}>{loading?'CHARGEMENT DES ATTAQUES…':'⚔ LANCER LE COMBAT'}</button></main></div>}
function Hp({p}){return <div className="pb-hp"><i style={{width:`${clamp(p.hp/p.maxHp*100,0,100)}%`}}/></div>}
function Fighter({p,back}){return <div className="pb-fighter"><img src={sprite(p,back)}alt={p.name}/><div className="pb-status"><b>{p.name}{p.mega?' ✦':''}{p.dynamax?' ⬢':''}{p.tera?' ◇':''}</b><span>Nv.{p.level}</span><Hp p={p}/><small>PV {p.hp}/{p.maxHp}</small>{p.item&&p.item!=='Aucun'&&<em>Objet : {p.item}</em>}</div></div>}
function Move({m,disabled,onClick}){return <button className="pb-move"disabled={disabled||m.pp<=0}onClick={onClick}><b>{m.name}</b><span>{TYPES[m.type]||m.type.toUpperCase()} · {m.damageClass==='status'?'STATUT':`Puiss. ${m.power}`}</span><small>PP {m.pp}/{m.maxPP} · {m.effect}</small></button>}
function Battle({p1,p2,onExit,items}){const[a,setA]=useState(p1),[b,setB]=useState(p2),[i1,setI1]=useState(0),[i2,setI2]=useState(0),[turn,setTurn]=useState(1),[log,setLog]=useState(['Le combat commence !']),[bag,setBag]=useState(false),[ended,setEnded]=useState(false);const x=a[i1],y=b[i2];const say=s=>setLog(v=>[...v.slice(-6),s]);const update=(side,arr)=>side===1?setA(arr):setB(arr);const attack=(side,m)=>{if(turn!==side||ended)return;const att=side===1?x:y,def=side===1?y:x;const A=att.stats[m.damageClass==='special'?'specialAttack':'attack']||50,D=def.stats[m.damageClass==='special'?'specialDefense':'defense']||50;const stab=att.types.includes(m.type)?1.5:1;const mod=att.mega?1.2:1;const dmg=m.power?Math.max(1,Math.floor((((2*att.level/5+2)*m.power*A/Math.max(1,D))/50+2)*stab*mod*(.85+Math.random()*.15))):0;const nm={...m,pp:Math.max(0,m.pp-1)},nd={...def,hp:Math.max(0,def.hp-dmg)},arr=(side===1?a:b).map((p,i)=>(side===1?i2:i1)===i?nd:p);if(side===1)setB(arr);else setA(arr);const nmoves=att.moves.map(z=>z.id===m.id?nm:z);update(side, (side===1?a:b).map((p,i)=>(side===1?i1:i2)===i?{...p,moves:nmoves}:p));say(`${att.name} utilise ${m.name}${dmg?` : ${dmg} dégâts.`:'.'}`);if(nd.hp<=0){say(`${def.name} est K.O. !`);const enemyArr=side===1?b:a,next=enemyArr.findIndex((p,i)=>i!==(side===1?i2:i1)&&p.hp>0);if(next>=0){side===1?setI2(next):setI1(next);setTurn(side===1?2:1)}else{setEnded(true);setTurn(0)}}else setTurn(side===1?2:1)};
const useItem=(side,item)=>{if(turn!==side||!items[item]||item==='Rappel'||item==='Rappel Max')return;const cur=side===1?x:y,heal=item==='Potion'?20:item==='Super Potion'?50:item==='Hyper Potion'?120:999;const np={...cur,hp:Math.min(cur.maxHp,cur.hp+heal),item:cur.item};if(side===1)setA(v=>v.map((p,i)=>i===i1?np:p));else setB(v=>v.map((p,i)=>i===i2?np:p));setBag(false);say(`${cur.name} utilise ${item}.`);setTurn(side===1?2:1)};
const choose=(side,n)=>{const arr=side===1?a:b;if(n===(side===1?i1:i2)||arr[n]?.hp<=0||turn!==side)return;side===1?setI1(n):setI2(n);setTurn(side===1?2:1);say(`${arr[n].name} entre au combat !`)};
const menu=(side,p)=><section className={`pb-menu ${turn===side?'active':''}`}><header><b>JOUEUR {side}</b><span>{p.name} · Nv.{p.level}</span></header><div className="pb-moves">{p.moves.map(m=><Move key={m.id}m={m}disabled={turn!==side}onClick={()=>attack(side,m)}/>)}</div><div className="pb-menu-row"><button onClick={()=>setBag(!bag)}disabled={turn!==side}>SAC</button>{(side===1?a:b).map((z,i)=><button key={i}disabled={z.hp<=0}className={(side===1?i1:i2)===i?'sel':''}onClick={()=>choose(side,i)}>{z.name}</button>)}</div>{bag&&turn===side&&<div className="pb-bag-pop">{Object.entries(items).filter(([,n])=>n>0).map(([it,n])=><button key={it}onClick={()=>useItem(side,it)}>{it} ×{n}</button>)}</div>}</section>;
return <div className="pb-screen pb-battle"><header className="pb-head"><div><b>{ended?'COMBAT TERMINÉ':`TOUR DU JOUEUR ${turn}`}</b><small>Menus totalement séparés · attaques individuelles · objets</small></div><button onClick={onExit}>QUITTER</button></header><main className="pb-arena"><div className="pb-side enemy"><Fighter p={y}/></div><div className="pb-side player"><Fighter p={x}back/></div></main><div className="pb-log">{log.map((s,i)=><div key={i}>{s}</div>)}</div><main className="pb-controls">{menu(1,x)}{menu(2,y)}</main></div>}
export default function BattlePersistent({onExit}){const[p1,setP1]=useState(null),[p2,setP2]=useState(null),[items,setItems]=useState({});return p1&&p2?<Battle p1={p1}p2={p2}items={items}onExit={onExit}/>:<Setup onExit={onExit}onStart={(a,b,it)=>{setP1(a);setP2(b);setItems(it)}}/>}
export function GmBattlePersistent({onExit}){return <BattlePersistent onExit={onExit}/>}
