import React,{useEffect,useMemo,useState}from'react';
import'./battle-real.css';
import{getHgssSpriteCandidates,spriteLabel}from'./hgssAssets.js';

const API='https://pokeapi.co/api/v2',DEX=1025;
const TYPES={normal:'NORMAL',fire:'FEU',water:'EAU',electric:'ÉLECTRIK',grass:'PLANTE',ice:'GLACE',fighting:'COMBAT',poison:'POISON',ground:'SOL',flying:'VOL',psychic:'PSY',bug:'INSECTE',rock:'ROCHE',ghost:'SPECTRE',dragon:'DRAGON',dark:'TÉNÈBRES',steel:'ACIER',fairy:'FÉE'};
const title=s=>String(s||'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const hpFor=(base,lv)=>Math.max(1,Math.floor((2*base*lv)/100)+lv+10);
const stat=(p,k)=>p.stats?.[k]||50;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function get(u){const r=await fetch(u);if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
const cache=new Map();
async function frSpecies(id,fallback){const k=`s${id}`;if(cache.has(k))return cache.get(k);try{const d=await get(`${API}/pokemon-species/${id}`);const n=d.names?.find(x=>x.language.name==='fr')?.name||fallback;cache.set(k,n);return n}catch{return fallback}}
async function frMove(id,fallback){const k=`m${id}`;if(cache.has(k))return cache.get(k);try{const d=await get(`${API}/move/${id}`);const n=d.names?.find(x=>x.language.name==='fr')?.name||fallback;cache.set(k,n);return n}catch{return fallback}}
async function hydrate(ref,level=50){const d=await get(ref.url||`${API}/pokemon/${ref.id}`),stats={};for(const s of d.stats||[])stats[s.stat.name.replace('special-attack','specialAttack').replace('special-defense','specialDefense')]=s.base_stat;const name=await frSpecies(d.id,title(d.name));const eligible=(d.moves||[]).flatMap(m=>(m.version_group_details||[]).filter(v=>v.move_learn_method.name==='level-up'&&v.level_learned_at<=level).map(v=>({url:m.move.url,level:v.level_learned_at}))).sort((a,b)=>a.level-b.level);const uniq=[];for(const m of eligible)if(!uniq.some(x=>x.url===m.url))uniq.push(m);let moves=(await Promise.all(uniq.slice(-12).map(async m=>{try{const x=await get(m.url);return{id:x.id,name:await frMove(x.id,title(x.name)),power:x.power||0,accuracy:x.accuracy||100,pp:x.pp||1,maxPP:x.pp||1,type:x.type?.name||'normal',damageClass:x.damage_class?.name||'status',priority:x.priority||0,critRate:x.meta?.crit_rate||0,effect:x.effect_entries?.find(e=>e.language.name==='fr')?.short_effect||x.effect_entries?.find(e=>e.language.name==='en')?.short_effect||'Aucun effet.'}}catch{return null}}))).filter(Boolean);moves=moves.filter((m,i,a)=>a.findIndex(x=>x.id===m.id)===i).slice(-4);if(!moves.length)moves=[{id:33,name:'Charge',power:40,accuracy:100,pp:35,maxPP:35,type:'normal',damageClass:'physical',priority:0,critRate:0,effect:'Inflige des dégâts.'}];const hp=hpFor(stats.hp||50,level);return{...ref,id:d.id,name,level,hp,maxHp:hp,stats,types:(d.types||[]).sort((a,b)=>a.slot-b.slot).map(x=>x.type.name),moves,heldItem:'Aucun',status:null,teraType:d.types?.[0]?.type?.name||'normal',dynamax:false,mega:false,tera:false}};

const chart={normal:{rock:.5,ghost:0,steel:.5},fire:{fire:.5,water:.5,grass:2,ice:2,bug:2,rock:.5,dragon:.5,steel:2},water:{fire:2,water:.5,grass:.5,ground:2,rock:2,dragon:.5},electric:{water:2,electric:.5,grass:.5,ground:0,flying:2,dragon:.5},grass:{fire:.5,water:2,grass:.5,poison:.5,ground:2,flying:.5,bug:.5,rock:2,dragon:.5,steel:.5},ice:{fire:.5,water:.5,grass:2,ice:.5,ground:2,flying:2,dragon:2,steel:.5},fighting:{normal:2,ice:2,poison:.5,flying:.5,psychic:.5,bug:.5,rock:2,ghost:0,dark:2,steel:2,fairy:.5},poison:{grass:2,poison:.5,ground:.5,rock:.5,ghost:.5,steel:0,fairy:2},ground:{fire:2,electric:2,grass:.5,poison:2,flying:0,bug:.5,rock:2,steel:2},flying:{electric:.5,grass:2,fighting:2,bug:2,rock:.5,steel:.5},psychic:{fighting:2,poison:2,psychic:.5,dark:0,steel:.5},bug:{fire:.5,grass:2,fighting:.5,poison:.5,flying:.5,psychic:2,ghost:.5,dark:2,steel:.5,fairy:.5},rock:{fire:2,ice:2,fighting:.5,ground:.5,flying:2,bug:2,steel:.5},ghost:{normal:0,psychic:2,ghost:2,dark:.5},dragon:{dragon:2,steel:.5,fairy:0},dark:{fighting:.5,psychic:2,ghost:2,dark:.5,fairy:.5},steel:{fire:.5,water:.5,electric:.5,ice:2,rock:2,steel:.5,fairy:2},fairy:{fire:.5,fighting:2,poison:.5,dragon:2,dark:2,steel:.5}};
const effectiveness=(m,d)=>(d.types||[]).reduce((v,t)=>v*(chart[m.type]?.[t]??1),1);
function damage(a,d,m){if(!m.power||m.damageClass==='status')return{damage:0,effect:1,critical:false,miss:false};if(Math.random()*100>=m.accuracy)return{damage:0,effect:1,critical:false,miss:true};const A=stat(a,m.damageClass==='special'?'specialAttack':'attack'),D=stat(d,m.damageClass==='special'?'specialDefense':'defense'),eff=effectiveness(m,d),stab=a.types.includes(m.type)?1.5:1,crit=Math.random()<((1+m.critRate)/24),g=(a.dynamax?1.5:1)*(a.mega?1.15:1)*(a.tera?1.2:1);const base=Math.floor((((2*a.level/5+2)*m.power*A/Math.max(1,D))/50)+2);return{damage:eff===0?0:Math.max(1,Math.floor(base*stab*g*(crit?1.5:1)*eff*(.85+Math.random()*.15))),effect:eff,critical:crit,miss:false}}

const FALLBACK_ITEMS=['Aucun','Potion','Super Potion','Hyper Potion','Potion Max','Guérison','Antidote','Anti-Para','Anti-Brûle','Anti-Gel','Réveil','Total Soin','Rappel','Rappel Max','Élixir','Max Élixir','Éther','Max Éther','PP Plus','PP Max','Baie Sitrus','Baie Prine','Baie Lum','Restes','Orbe Vie','Bandeau Choix','Lunettes Choix','Mouchoir Choix','Veste de Combat','Ceinture Force','Ceinture Pro'];
function Hp({p,small=false}){return <div className={`hp ${small?'small':''}`}><i style={{width:`${clamp(100*p.hp/p.maxHp,0,100)}%`}}/></div>}
function Sprite({pokemon,side}){const[i,setI]=useState(0),src=getHgssSpriteCandidates(pokemon,side)[i];return <div className="battle-sprite">{src&&<img src={src} alt={spriteLabel(pokemon.name,side)} onError={()=>setI(x=>x+1)}/>}</div>}
function TeamStrip({team,active,onSelect,label}){const alive=team.filter(p=>p&&p.hp>0).length;return <div className="team-strip"><b>{label}<br/>{alive}/6</b>{Array.from({length:6},(_,i)=>{const p=team[i];return <button key={i} disabled={!p||p.hp<=0} className={i===active?'active':''} onClick={()=>onSelect(i)}>{p?<><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png`} alt=""/><span>{p.name}</span><Hp p={p} small/></>:<em>—</em>}</button>})}</div>}

function Picker({team,setTeam,titleText}){const[list,setList]=useState([]),[names,setNames]=useState({}),[q,setQ]=useState(''),[page,setPage]=useState(0);useEffect(()=>{get(`${API}/pokemon?limit=${DEX}`).then(d=>setList(d.results.map((x,i)=>({id:i+1,name:title(x.name),url:x.url})))).catch(()=>{})},[]);const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return s?list.filter(p=>String(p.id).includes(s)||p.name.toLowerCase().includes(s)||names[p.id]?.toLowerCase().includes(s)):list},[list,q,names]);const pages=Math.max(1,Math.ceil(filtered.length/60)),items=filtered.slice(page*60,page*60+60);useEffect(()=>setPage(0),[q]);useEffect(()=>{const missing=items.filter(p=>!names[p.id]).slice(0,15);if(missing.length)Promise.all(missing.map(async p=>[p.id,await frSpecies(p.id,p.name)])).then(a=>setNames(n=>({...n,...Object.fromEntries(a)})))},[items,names]);return <div className="picker"><header><b>{titleText}</b><span>{list.length}/1025 Pokémon</span></header><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nom ou numéro partiel : 10 → 10, 100, 101, 102… 1000…"/><div className="pager"><button disabled={!page} onClick={()=>setPage(page-1)}>‹</button><b>{page+1}/{pages}</b><button disabled={page>=pages-1} onClick={()=>setPage(page+1)}>›</button></div><div className="picker-grid">{items.map(p=>{const chosen=team.some(x=>x?.id===p.id);return <button key={p.id} className={chosen?'chosen':''} onClick={()=>{if(chosen||team.length>=6)return;setTeam([...team,{...p,level:50,heldItem:'Aucun'}])}}><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png`} alt=""/><strong>#{String(p.id).padStart(4,'0')}</strong><span>{names[p.id]||p.name}</span></button>})}</div></div>}

function ConfigureTeam({label,team,setTeam,items}){const[open,setOpen]=useState(false);const update=(i,k,v)=>setTeam(team.map((p,j)=>j===i?{...p,[k]:v}:p));return <section className="configure"><header><b>{label}</b><span>{team.length}/6</span></header>{team.map((p,i)=><div className="configured" key={`${p.id}-${i}`}><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png`} alt=""/><div className="configured-main"><strong>{p.name}</strong><label>Niveau <input type="number" min="1" max="100" value={p.level||50} onChange={e=>update(i,'level',clamp(Number(e.target.value)||1,1,100))}/></label><label>Objet tenu <select value={p.heldItem||'Aucun'} onChange={e=>update(i,'heldItem',e.target.value)}>{items.map(x=><option key={x}>{x}</option>)}</select></label></div><button className="remove" onClick={()=>setTeam(team.filter((_,j)=>j!==i))}>×</button></div>)}<button className="add-pokemon" disabled={team.length>=6} onClick={()=>setOpen(true)}>+ CHOISIR UN POKÉMON</button>{open&&<div className="modal"><div className="modal-inner"><button className="close" onClick={()=>setOpen(false)}>×</button><Picker titleText={`CHOISIR ${label}`} team={team} setTeam={setTeam}/></div></div>}</section>}

function Setup({onStart,onExit}){const[player,setPlayer]=useState([]),[enemy,setEnemy]=useState([]),[gimmick,setGimmick]=useState('none'),[items,setItems]=useState(FALLBACK_ITEMS),[loading,setLoading]=useState(false);useEffect(()=>{get(`${API}/item?limit=2000`).then(async d=>{const fr=await Promise.all(d.results.map(async x=>{try{const z=await get(x.url);return z.names?.find(n=>n.language.name==='fr')?.name||title(x.name)}catch{return title(x.name)}}));setItems(['Aucun',...fr.filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i)])}).catch(()=>{})},[]);const start=async()=>{if(!player.length||!enemy.length)return;setLoading(true);try{const p=await Promise.all(player.map(x=>hydrate(x,x.level||50))),e=await Promise.all(enemy.map(x=>hydrate(x,x.level||50)));onStart(p,e,gimmick)}finally{setLoading(false)}};return <div className="setup-shell"><header className="setup-header"><button onClick={onExit}>← QUITTER</button><div><b>COMBAT POKÉMON · PRÉPARATION</b><small>Équipe complète, niveaux et objets individuels</small></div><span>1025 POKÉMON</span></header><div className="setup-grid"><ConfigureTeam label="ÉQUIPE ALLIÉE" team={player} setTeam={setPlayer} items={items}/><ConfigureTeam label="ÉQUIPE ENNEMIE" team={enemy} setTeam={setEnemy} items={items}/><section className="setup-card"><h3>RÈGLES DE COMBAT</h3><p>Les deux équipes peuvent avoir jusqu'à 6 Pokémon. Les niveaux, objets et attaques sont appliqués individuellement. Le calcul utilise puissance, précision, STAB, types, critique et défenses.</p><div className="gimmick-select">{[['none','AUCUN'],['mega','MÉGA'],['dynamax','DYNAMAX'],['tera','TÉRACRISTAL']].map(([v,n])=><button className={gimmick===v?'selected':''} key={v} onClick={()=>setGimmick(v)}>{n}</button>)}</div></section><section className="setup-card"><h3>CONTENU</h3><p>Recherche numérique partielle, noms français, sprites HGSS disponibles, attaques françaises, PP, objets de soin/statut/PP et objets tenus.</p><p><b>{items.length}</b> objets actuellement disponibles dans le Pokédex d'objets.</p></section></div><footer className="setup-footer"><span>Allié : {player.length}/6</span><span>Ennemi : {enemy.length}/6</span><button className="launch" disabled={!player.length||!enemy.length||loading} onClick={start}>{loading?'CHARGEMENT…':'⚔ LANCER LE COMBAT'}</button></footer></div>}

function Battle({playerTeam,enemyTeam,onExit,gimmick}){const[player,setPlayer]=useState(playerTeam),[enemy,setEnemy]=useState(enemyTeam),[pi,setPi]=useState(0),[ei,setEi]=useState(0),[log,setLog]=useState(['Le combat commence !']),[busy,setBusy]=useState(false),[info,setInfo]=useState(null),[bag,setBag]=useState(false),[usedGimmick,setUsedGimmick]=useState(false);const me=player[pi],foe=enemy[ei];const say=m=>setLog(x=>[...x.slice(-14),m]);const setP=(arr,i,p)=>arr.map((x,j)=>j===i?p:x);const perform=(att,def,m)=>damage(att,def,m);const aiMove=async(current,target,enemyArr,playerArr)=>{const choices=current.moves.filter(x=>x.pp>0),m=choices[Math.floor(Math.random()*choices.length)]||current.moves[0];await sleep(550);const r=perform(current,target,m);if(r.miss){say(`${current.name} utilise ${m.name}, mais l'attaque échoue !`);return{enemyArr,playerArr}};const nd=r.damage?{...target,hp:Math.max(0,target.hp-r.damage)}:target;const np=setP(playerArr,pi,nd);say(r.damage?`${current.name} utilise ${m.name} : ${r.damage} dégâts.`:`${current.name} utilise ${m.name}. ${m.effect}`);if(r.critical)say('Coup critique !');if(r.effect>1)say('C'est super efficace !');if(r.effect>0&&r.effect<1)say('Ce n’est pas très efficace…');return{enemyArr,playerArr:np}};
const doMove=async m=>{if(busy||!me||!foe||me.hp<=0)return;setBusy(true);const used={...m,pp:Math.max(0,m.pp-1)},newMe={...me,moves:me.moves.map(x=>x.id===m.id?used:x)},r=perform(newMe,foe,used);let pArr=setP(player,pi,newMe),eArr=enemy;if(r.miss){say(`${me.name} utilise ${m.name}, mais l'attaque échoue !`)}else{const nd={...foe,hp:Math.max(0,foe.hp-r.damage)};eArr=setP(enemy,ei,nd);say(`${me.name} utilise ${m.name}${r.damage?` et inflige ${r.damage} dégâts.`:'.'}`);if(r.critical)say('Coup critique !');if(r.effect>1)say('C’est super efficace !');if(r.effect>0&&r.effect<1)say('Ce n’est pas très efficace…');if(r.effect===0)say('Cela n’a aucun effet !');setInfo(m)}setPlayer(pArr);setEnemy(eArr);await sleep(700);let nextEnemy=eArr[ei];if(nextEnemy?.hp<=0){say(`${nextEnemy.name} est K.O. !`);const n=eArr.findIndex((p,i)=>i!==ei&&p?.hp>0);if(n>=0){setEi(n);say(`L'ennemi envoie ${eArr[n].name} !`);await sleep(450)}else{say('Victoire !');setBusy(false);return}}const currentEnemy=eArr[nxtIndex(eArr,ei)];const targetPlayer=pArr[pi];if(currentEnemy&&targetPlayer?.hp>0){const out=await aiMove(currentEnemy,targetPlayer,currentEnemy?eArr:enemy,pArr);pArr=out.playerArr;setPlayer(pArr);const damaged=pArr[pi];if(damaged?.hp<=0){say(`${damaged.name} est K.O. !`);const n=pArr.findIndex((p,i)=>i!==pi&&p?.hp>0);if(n>=0){setPi(n);say(`À toi, ${pArr[n].name} !`)}}}setBusy(false)};
const useGimmick=()=>{if(usedGimmick||gimmick==='none'||!me)return;const p={...me,[gimmick==='mega'?'mega':gimmick==='dynamax'?'dynamax':'tera']:true};setPlayer(setP(player,pi,p));setUsedGimmick(true);say(`${me.name} utilise ${gimmick==='mega'?'la Méga-Évolution':gimmick==='dynamax'?'le Dynamax':'la Téracristallisation'} !`)};
const useItem=name=>{if(!me)return;let p={...me};if(name==='Potion')p.hp=Math.min(p.maxHp,p.hp+20);else if(name==='Super Potion')p.hp=Math.min(p.maxHp,p.hp+50);else if(name==='Hyper Potion')p.hp=Math.min(p.maxHp,p.hp+120);else if(name==='Potion Max'||name==='Guérison')p.hp=p.maxHp;else if(name==='Rappel'||name==='Rappel Max'){const i=player.findIndex(x=>x&&x.hp<=0);if(i>=0){const q={...player[i],hp:Math.max(1,Math.floor(player[i].maxHp*(name==='Rappel Max'?1:.5)))};setPlayer(setP(player,i,q));say(`Vous utilisez ${name} sur ${q.name}.`);setBag(false);return}}else if(['Élixir','Max Élixir','Éther','Max Éther'].includes(name))p.moves=p.moves.map(m=>({...m,pp:m.maxPP}));else{say(`${name} est utilisé, mais son effet nécessite une cible.`);setBag(false);return}setPlayer(setP(player,pi,p));say(`Vous utilisez ${name} sur ${p.name}.`);setBag(false)};
return <div className="battle-shell"><header className="battle-header"><button onClick={onExit}>← QUITTER</button><div><b>COMBAT POKÉMON</b><small>{gimmick==='none'?'Combat standard':gimmick==='mega'?'Méga-Évolution':gimmick==='dynamax'?'Dynamax':'Téracristallisation'}</small></div><span>{player.filter(p=>p.hp>0).length}/6 · {enemy.filter(p=>p.hp>0).length}/6</span></header><TeamStrip team={enemy} active={ei} onSelect={setEi} label="ENNEMI"/><div className="battle-stage"><div className="battle-bg"/><div className="platform enemy-platform"/><div className="platform player-platform"/><div className="fighter foe"><div className="status-box"><b>{foe?.name||'—'}</b><span>Nv. {foe?.level||'—'}</span><Hp p={foe||{hp:0,maxHp:1}}/><small>{foe?.types?.map(t=>TYPES[t]).join(' / ')} · {foe?.heldItem||'Aucun'}</small></div>{foe&&<Sprite pokemon={foe} side="back"/>}</div><div className="fighter hero"><div className="status-box"><b>{me?.name||'—'}</b><span>Nv. {me?.level||'—'}</span><Hp p={me||{hp:0,maxHp:1}}/><small>{me?.types?.map(t=>TYPES[t]).join(' / ')} · {me?.heldItem||'Aucun'}</small></div>{me&&<Sprite pokemon={me} side="front"/>}</div></div><TeamStrip team={player} active={pi} onSelect={setPi} label="ALLIÉ"/><div className="gimmick-bar"><button disabled={usedGimmick||gimmick==='none'||busy} onClick={useGimmick}>{gimmick==='mega'?'MÉGA':gimmick==='dynamax'?'DYNAMAX':gimmick==='tera'?'TÉRA':'—'}</button><span>{me?.heldItem&&me.heldItem!=='Aucun'?`Objet tenu : ${me.heldItem}`:'Aucun objet tenu'}</span></div><div className="battle-info"><div className="battle-log">{log.map((x,i)=><div key={i}>{x}</div>)}</div><div className="move-info">{me?.moves.map(m=><div key={m.id} onMouseEnter={()=>setInfo(m)}><b>{m.name}</b><span>{TYPES[m.type]} · {m.damageClass==='status'?'STATUT':`${m.power} puissance`}</span><small>PP {m.pp}/{m.maxPP} · {m.accuracy}% · {m.effect}</small></div>)}</div></div><div className="battle-actions"><div className="moves-grid">{me?.moves.map(m=><button key={m.id} disabled={busy||m.pp<=0||!foe||foe.hp<=0} onClick={()=>doMove(m)}><strong>{m.name}</strong><span>{TYPES[m.type]} · PP {m.pp}/{m.maxPP}</span></button>)}</div><div className="actions-side"><button disabled={busy} onClick={()=>setBag(true)}>SAC</button><button disabled={busy} onClick={()=>{const n=player.findIndex((p,i)=>i!==pi&&p.hp>0);if(n>=0){setPi(n);say(`Reviens, ${me.name} ! À toi, ${player[n].name} !`)}}}>POKÉMON</button><button disabled={busy} onClick={()=>say('Vous ne pouvez pas fuir ce combat.')}>FUITE</button></div></div>{info&&<div className="move-tooltip"><b>{info.name}</b> — {info.effect}</div>}{bag&&<div className="modal"><section className="bag"><button className="close" onClick={()=>setBag(false)}>×</button><h2>SAC</h2><div>{FALLBACK_ITEMS.slice(1).map(x=><button key={x} onClick={()=>useItem(x)}>{x}</button>)}</div></section></div>}</div>}
function nxtIndex(arr,i){return arr[i]?.hp>0?i:arr.findIndex(p=>p?.hp>0)}

export default function BattleViewReal({onExit}){const[start,setStart]=useState(null);if(start)return <Battle playerTeam={start.p} enemyTeam={start.e} gimmick={start.g} onExit={()=>setStart(null)}/>;return <Setup onExit={onExit} onStart={(p,e,g)=>setStart({p,e,g})}/>}
export function GmBattleViewReal({onExit}){return <BattleViewReal onExit={onExit}/>}
