import React,{useEffect,useMemo,useState}from'react';
import{getHgssSpriteCandidates,spriteLabel}from'./hgssAssets.js';

const POKEDEX_SIZE=1025;
const API='https://pokeapi.co/api/v2';
const fallbackPokemon=[{id:25,name:'Pikachu',level:12,hp:35,maxHp:35,type:'ÉLECTRIK',icon:'⚡',moves:[['Éclair',7],['Vive-Attaque',5],['Tonnerre',10],['Rugissement',0]]},{id:1,name:'Bulbizarre',level:10,hp:30,maxHp:30,type:'PLANTE / POISON',icon:'🌱',moves:[['Charge',5],['Fouet Lianes',7],['Vampigraine',0],['Rugissement',0]]}];

function titleName(name){return name.split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ')}
function iconFor(type=''){return ({ÉLECTRIK:'⚡',FEU:'🔥',EAU:'💧',PLANTE:'🌱',GLACE:'❄️',PSY:'🔮',SPECTRE:'👻',DRAGON:'🐉',INSECTE:'🐛',VOL:'🪽',POISON:'☠️',SOL:'⛰️',ROCHE:'🪨',COMBAT:'🥊',ACIER:'⚙️',TÉNÈBRES:'🌑',FÉE:'✨',NORMAL:'●'})[type]||'●'}
function formatType(t){return ({electric:'ÉLECTRIK',fire:'FEU',water:'EAU',grass:'PLANTE',ice:'GLACE',psychic:'PSY',ghost:'SPECTRE',dragon:'DRAGON',bug:'INSECTE',flying:'VOL',poison:'POISON',ground:'SOL',rock:'ROCHE',fighting:'COMBAT',steel:'ACIER',dark:'TÉNÈBRES',fairy:'FÉE',normal:'NORMAL'})[t]||t.toUpperCase()}

function makePokemon(data){const types=(data.types||[]).sort((a,b)=>a.slot-b.slot).map(x=>formatType(x.type.name));const hp=data.stats?.find(x=>x.stat.name==='hp')?.base_stat||50;return{id:data.id,name:titleName(data.name),level:10,hp,maxHp:hp,type:types.join(' / '),icon:iconFor(types[0]),sprite:data.sprites?.front_default||null,moves:[['Charge',5],['Attaque',7],['Capacité',10],['Défense',0]]}}
function Hp({hp,maxHp}){const ratio=Math.max(0,Math.min(100,hp/maxHp*100));return <div className="hp hgss-hp"><i style={{width:`${ratio}%`}}/></div>}
function Sprite({pokemon,side}){const[attempt,setAttempt]=useState(0);const candidates=[...(pokemon.sprite?[pokemon.sprite]:[]),...getHgssSpriteCandidates(pokemon.name,side)];const src=candidates[attempt];return <div className={`hgss-sprite ${side}`}>{src?<img src={src} alt={spriteLabel(pokemon.name,side)} onError={()=>setAttempt(a=>a+1)}/>:<div className="sprite-fallback" aria-label={pokemon.name}>{pokemon.icon}</div>}</div>}
function Fighter({pokemon,enemy=false}){return <div className={`fighter ${enemy?'enemy':'player'}`}><div className="hgss-status"><div className="status-line"><b>{pokemon.name}</b><span>♂</span><strong>Lv{pokemon.level}</strong></div><Hp hp={pokemon.hp} maxHp={pokemon.maxHp}/><small>HP {Math.max(0,pokemon.hp)}/{pokemon.maxHp}</small></div><Sprite pokemon={pokemon} side={enemy?'front':'back'}/></div>}
function PartySprite({pokemon}){return <Sprite pokemon={pokemon} side="front"/>}
function TeamStrip({team,selected,setSelected}){return <div className="team-strip hgss-party">{team.map((p,i)=><button key={`${p.id}-${i}`} className={i===selected?'active':''} disabled={p.hp<=0} onClick={()=>setSelected(i)}><span className="party-ball"><PartySprite pokemon={p}/></span><div><b>{p.name}</b><small>Lv{p.level}</small></div><div className="party-hp"><Hp hp={p.hp} maxHp={p.maxHp}/><small>{Math.max(0,p.hp)}/{p.maxHp}</small></div></button>)}</div>}
function BattleHud({message,turn,children}){return <><div className="hgss-dialog"><b>{message}</b><small>{turn==='player'?'À vous de jouer.':'Le PNJ joue…'}</small></div>{children}</>}

function PokemonPicker({label,selected,onSelect,excludeId}){const[list,setList]=useState([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let cancelled=false;fetch(`${API}/pokemon?limit=${POKEDEX_SIZE}&offset=0`).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(d=>{if(!cancelled)setList(d.results.map((x,i)=>({id:i+1,name:titleName(x.name),url:x.url}))) }).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return list.filter(p=>p.id!==excludeId&&(!q||p.name.toLowerCase().includes(q)||String(p.id)===q)).slice(0,80)},[list,query,excludeId]);return <div className="pokemon-picker"><div className="pokemon-picker-title"><b>{label}</b><span>{list.length||POKEDEX_SIZE} / {POKEDEX_SIZE}</span></div><input value={query}onChange={e=>setQuery(e.target.value)}placeholder="Rechercher par nom ou numéro…"/><div className="pokemon-picker-list">{loading&&<small>Chargement du Pokédex national…</small>}{error&&<small>Impossible de charger le Pokédex : {error}</small>}{!loading&&!error&&!filtered.length&&<small>Aucun Pokémon trouvé.</small>}{filtered.map(p=><button key={p.id} className={selected?.id===p.id?'chosen':''} onClick={()=>onSelect(p)}><strong>#{String(p.id).padStart(4,'0')}</strong><span>{p.name}</span></button>)}</div></div>}

async function hydratePokemon(ref){if(ref?.hp&&ref?.maxHp&&ref?.moves)return ref;const r=await fetch(ref.url||`${API}/pokemon/${ref.id}`);if(!r.ok)throw Error('Pokémon introuvable');return makePokemon(await r.json())}

export default function BattleView({onExit}){
 const[player,setPlayer]=useState(fallbackPokemon),[enemy,setEnemy]=useState([fallbackPokemon[1]]),[selected,setSelected]=useState(0),[turn,setTurn]=useState('player'),[message,setMessage]=useState('Que doit faire Pikachu ?'),[panel,setPanel]=useState(null),[picker,setPicker]=useState(null);
 const activePlayer=player[selected],activeEnemy=enemy.find(p=>p.hp>0)||enemy[0];
 const choosePlayer=async ref=>{const p=await hydratePokemon(ref);setPlayer([p]);setSelected(0);setMessage(`Que doit faire ${p.name} ?`);setPicker(null)};
 const chooseEnemy=async ref=>{const p=await hydratePokemon(ref);setEnemy([p]);setMessage(`${p.name} apparaît !`);setPicker(null)};
 const enemyTurn=()=>setTimeout(()=>{if(!activeEnemy||activeEnemy.hp<=0){setTurn('player');setMessage('Victoire !');return}const d=Math.min(activePlayer.hp,4);setPlayer(t=>t.map((p,i)=>i===selected?{...p,hp:Math.max(0,p.hp-d)}:p));setMessage(`${activeEnemy.name} attaque !`);setTurn('player')},450);
 const attack=(name,power)=>{if(turn!=='player'||!activePlayer||activePlayer.hp<=0)return;setPanel(null);const d=Math.min(activeEnemy.hp,power);setEnemy(t=>t.map(p=>p.name===activeEnemy.name?{...p,hp:p.hp-d}:p));setMessage(`${activePlayer.name} utilise ${name} !`);setTurn('enemy');setTimeout(()=>{if(activeEnemy.hp-d<=0){setMessage(`${activeEnemy.name} est K.O. !`);setTurn('player')}else enemyTurn()},300)};
 return <section className="battle-screen hgss-battle"><header className="battle-topbar hgss-battle-top"><div><small>COMBAT · INTERFACE JOUEUR</small><h2>Combat Pokémon</h2></div><div className="battle-mode"><b>JOUEUR</b><span>Pokédex national · 1025 Pokémon</span></div><button onClick={onExit}>QUITTER</button></header>{picker&&<div className="battle-picker-overlay"><div className="battle-picker-modal"><button className="battle-picker-close" onClick={()=>setPicker(null)}>×</button><PokemonPicker label={picker==='player'?'CHOISIR LE POKÉMON ATTAQUANT':'CHOISIR LE POKÉMON DÉFENSIF'} selected={picker==='player'?activePlayer:activeEnemy} onSelect={picker==='player'?choosePlayer:chooseEnemy} excludeId={picker==='player'?activeEnemy?.id:activePlayer?.id}/></div></div>}
 <div className="battle-field hgss-field"><div className="hgss-sky"/><div className="hgss-ground enemy-ground"/><div className="hgss-ground player-ground"/><Fighter pokemon={activeEnemy} enemy/><Fighter pokemon={activePlayer}/></div>
 <BattleHud message={message} turn={turn}><div className="battle-controls hgss-controls"><div className="battle-actions hgss-actions"><button className="battle-action primary" disabled={turn!=='player'} onClick={()=>setPanel('moves')}>COMBAT</button><button className="battle-action" disabled={turn!=='player'} onClick={()=>setPanel('bag')}>SAC</button><button className="battle-action" disabled={turn!=='player'} onClick={()=>setPicker('player')}>POKÉMON</button><button className="battle-action" disabled={turn!=='player'} onClick={()=>setPicker('enemy')}>CHOISIR DÉFENSEUR</button>{panel==='moves'&&<div className="battle-subpanel hgss-moves"><b>CHOISIR UNE ATTAQUE</b>{activePlayer.moves.map(([n,p])=><button key={n} disabled={!p} onClick={()=>attack(n,p)}><strong>{n}</strong><small>{p?'Puissance '+p:'—'}</small></button>)}</div>}{panel==='bag'&&<div className="battle-subpanel hgss-moves"><b>SAC</b><button onClick={()=>{setPlayer(t=>t.map((p,i)=>i===selected?{...p,hp:Math.min(p.maxHp,p.hp+10)}:p));setMessage('Potion utilisée : +10 HP');setPanel(null)}}><strong>Potion</strong><small>+10 HP</small></button></div>}</div><TeamStrip team={player} selected={selected} setSelected={setSelected}/></div></BattleHud></section>}

export function GmBattleView({onExit}){
 const[setup,setSetup]=useState(true),[enemyChoice,setEnemyChoice]=useState(null),[playerChoice,setPlayerChoice]=useState(null),[enemies,setEnemies]=useState([]),[players,setPlayers]=useState(fallbackPokemon),[selected,setSelected]=useState(0),[target,setTarget]=useState(0),[message,setMessage]=useState('');
 const current=enemies[selected],targetPlayer=players[target];
 const launch=async()=>{if(!enemyChoice||!playerChoice)return;const[e,p]=await Promise.all([hydratePokemon(enemyChoice),hydratePokemon(playerChoice)]);setEnemies([e]);setPlayers([p]);setSelected(0);setTarget(0);setMessage(`${e.name} affronte ${p.name} !`);setSetup(false)};
 if(setup)return <section className="battle-screen gm-battle hgss-battle"><header className="battle-topbar hgss-battle-top"><div><small>COMBAT · INTERFACE MJ</small><h2>Préparer le combat</h2></div><div className="battle-mode gm"><b>MJ</b><span>1025 Pokémon disponibles</span></div><button onClick={onExit}>QUITTER</button></header><div className="gm-setup hgss-setup"><div className="hgss-panel-title">CHOISIR L'ATTAQUANT ET LE DÉFENSEUR</div><div className="gm-picker-columns"><PokemonPicker label="POKÉMON ATTAQUANT / JOUEUR" selected={playerChoice} onSelect={setPlayerChoice} excludeId={enemyChoice?.id}/><PokemonPicker label="POKÉMON DÉFENSIF / PNJ" selected={enemyChoice} onSelect={setEnemyChoice} excludeId={playerChoice?.id}/></div><button className="gm-launch" disabled={!enemyChoice||!playerChoice} onClick={launch}>⚔ LANCER LE COMBAT</button></div></section>;
 const damage=(amount,label)=>{if(!current||current.hp<=0||!targetPlayer||targetPlayer.hp<=0)return;const d=Math.min(targetPlayer.hp,amount);setPlayers(t=>t.map((p,i)=>i===target?{...p,hp:Math.max(0,p.hp-d)}:p));setMessage(`${current.name} ${label} sur ${targetPlayer.name} : -${d} HP.`)};
 return <section className="battle-screen gm-battle hgss-battle"><header className="battle-topbar hgss-battle-top"><div><small>COMBAT · INTERFACE MJ</small><h2>Gestion du combat</h2></div><div className="battle-mode gm"><b>MJ</b><span>1025 Pokémon disponibles</span></div><button onClick={onExit}>QUITTER</button></header><div className="gm-battle-stage"><div className="gm-stage-enemy"><span>PNJ ACTIF</span>{current&&<><Sprite pokemon={current} side="front"/><h3>{current.name} · Lv{current.level}</h3><Hp hp={current.hp} maxHp={current.maxHp}/></>}</div><div className="gm-vs">VS</div><div className="gm-stage-player"><span>CIBLE JOUEUR</span>{targetPlayer&&<><Sprite pokemon={targetPlayer} side="back"/><h3>{targetPlayer.name} · Lv{targetPlayer.level}</h3><Hp hp={targetPlayer.hp} maxHp={targetPlayer.maxHp}/></>}</div></div><div className="gm-command hgss-gm-command"><div className="gm-target-list"><b>PNJ</b>{enemies.map((p,i)=><button className={i===selected?'selected':''} key={p.name} onClick={()=>setSelected(i)}><PartySprite pokemon={p}/>{p.name}</button>)}</div><div className="gm-target-list"><b>JOUEURS</b>{players.map((p,i)=><button className={i===target?'selected target':''} key={p.name} onClick={()=>setTarget(i)}><PartySprite pokemon={p}/>{p.name}</button>)}</div><div className="gm-buttons"><button onClick={()=>damage(5,'attaque')}>ATTAQUER</button><button onClick={()=>damage(8,'utilise sa capacité')}>CAPACITÉ</button><button onClick={()=>setMessage(`${current?.name} se défend.`)}>DÉFENDRE</button><button onClick={()=>setSetup(true)}>CHANGER DE POKÉMON</button></div><p>{message}</p></div></section>;
}
