import React,{useMemo,useState}from'react';

const initialPlayer=[
 {name:'Pikachu',level:12,hp:32,maxHp:35,type:'ÉLECTRIK',icon:'⚡',moves:[['Éclair',7],['Vive-Attaque',5],['Tonnerre',10],['Rugissement',0]]},
 {name:'Bulbizarre',level:10,hp:24,maxHp:30,type:'PLANTE / POISON',icon:'🌱',moves:[['Charge',5],['Fouet Lianes',7],['Vampigraine',0],['Rugissement',0]]}
];
const initialEnemy=[
 {name:'Rattata',level:9,hp:25,maxHp:25,type:'NORMAL',icon:'🐭'},
 {name:'Roucool',level:8,hp:20,maxHp:20,type:'VOL',icon:'🪽'}
];

function Hp({hp,maxHp}){const ratio=Math.max(0,Math.min(100,hp/maxHp*100));return <div className="hp"><i style={{width:`${ratio}%`}}/></div>}
function Fighter({pokemon,enemy=false}){return <div className={`fighter ${enemy?'enemy':'player'}`}><div className="fighter-card"><div><b>{pokemon.name}</b><span>♂ · Nv.{pokemon.level}</span></div><Hp hp={pokemon.hp} maxHp={pokemon.maxHp}/><small>PV {Math.max(0,pokemon.hp)} / {pokemon.maxHp}</small></div><div className="battle-sprite" aria-label={pokemon.name}>{pokemon.icon}</div></div>}

function TeamStrip({team,selected,setSelected}){return <div className="team-strip">{team.map((p,i)=><button key={p.name} className={i===selected?'active':''} disabled={p.hp<=0} onClick={()=>setSelected(i)}><span>{p.icon}</span><b>{p.name}</b><small>{Math.max(0,p.hp)}/{p.maxHp}</small></button>)}</div>}

export default function BattleView({onExit}){
 const [player,setPlayer]=useState(initialPlayer);const [enemy,setEnemy]=useState(initialEnemy);const [selected,setSelected]=useState(0);const [turn,setTurn]=useState('player');const [message,setMessage]=useState('Que doit faire Pikachu ?');const [log,setLog]=useState(['Un combat commence !']);const [panel,setPanel]=useState(null);
 const activePlayer=player[selected];const activeEnemy=enemy.find(p=>p.hp>0)||enemy[0];
 const addLog=(text)=>setLog(l=>[text,...l].slice(0,5));
 const enemyTurn=(nextEnemy)=>{setTimeout(()=>{if(!nextEnemy||nextEnemy.hp<=0){setTurn('player');setMessage('Victoire !');return;}const target=selected;const damage=Math.min(player[target].hp,4);setPlayer(t=>t.map((p,i)=>i===target?{...p,hp:Math.max(0,p.hp-damage)}:p));addLog(`${nextEnemy.name} riposte : -${damage} PV`);setMessage(`${nextEnemy.name} attaque !`);setTurn('player');},500)};
 const attack=(name,power)=>{if(turn!=='player'||!activePlayer||activePlayer.hp<=0)return;setPanel(null);const damage=Math.min(activeEnemy.hp,power);setEnemy(t=>t.map(p=>p.name===activeEnemy.name?{...p,hp:p.hp-damage}:p));addLog(`${activePlayer.name} utilise ${name} : -${damage} PV`);setMessage(`${activePlayer.name} utilise ${name} !`);setTurn('enemy');const nextHp=activeEnemy.hp-damage;setTimeout(()=>{if(nextHp<=0){const next=enemy.find(p=>p.name!==activeEnemy.name&&p.hp>0);if(next){setMessage(`Le PNJ envoie ${next.name} !`);setTurn('player')}else{setMessage('Victoire !');setTurn('player')}return}enemyTurn(activeEnemy)},300)};
 const switchPokemon=()=>{const next=player.findIndex((p,i)=>i!==selected&&p.hp>0);if(next<0){setMessage('Aucun autre Pokémon disponible.');return}setSelected(next);setMessage(`Go, ${player[next].name} !`);addLog(`Changement vers ${player[next].name}`);setPanel(null)};
 return <section className="battle-screen"><header className="battle-topbar"><div><small>COMBAT · VUE JOUEUR</small><h2>Combat Pokémon</h2></div><div className="battle-mode"><b>JOUEUR</b><span>commandes du personnage</span></div><button onClick={onExit}>QUITTER</button></header><div className="battle-field"><div className="battle-background"/><Fighter pokemon={activeEnemy} enemy/><Fighter pokemon={activePlayer}/><div className="battle-name enemy-name">PNJ · {activeEnemy.name}</div><div className="battle-name player-name">VOUS · {activePlayer.name}</div></div><div className="battle-message"><b>{message}</b><small>{turn==='player'?'À votre tour':'Tour du PNJ…'}</small></div><div className="battle-controls"><div className="battle-actions"><button className="battle-action primary" disabled={turn!=='player'} onClick={()=>setPanel('moves')}>⚔ COMBAT</button><button className="battle-action" disabled={turn!=='player'} onClick={()=>setPanel('bag')}>● SAC</button><button className="battle-action" disabled={turn!=='player'} onClick={switchPokemon}>↻ POKÉMON</button><button className="battle-action" disabled={turn!=='player'} onClick={()=>{setMessage('Vous tentez de fuir…');addLog('Tentative de fuite');}}>↗ FUITE</button>{panel==='moves'&&<div className="battle-subpanel"><b>CHOISIR UNE ATTAQUE</b>{activePlayer.moves.map(([name,power])=><button key={name} disabled={power===0} onClick={()=>attack(name,power)}>{name}<small>{power?'Puissance '+power:'—'}</small></button>)}</div>}{panel==='bag'&&<div className="battle-subpanel"><b>SAC</b><button onClick={()=>{setMessage('Potion utilisée : +10 PV');setPlayer(t=>t.map((p,i)=>i===selected?{...p,hp:Math.min(p.maxHp,p.hp+10)}:p));addLog('Potion utilisée');setPanel(null)}}>Potion<small>+10 PV</small></button><button onClick={()=>{setMessage('Poké Ball prête.');addLog('Poké Ball sélectionnée');setPanel(null)}}>Poké Ball<small>capture</small></button></div>}</div><TeamStrip team={player} selected={selected} setSelected={setSelected}/><aside className="battle-log"><b>JOURNAL</b>{log.map((x,i)=><span key={`${x}-${i}`}>{x}</span>)}</aside></div></section>
}

export function GmBattleView({onExit}){
 const [enemies,setEnemies]=useState(initialEnemy);const [players,setPlayers]=useState(initialPlayer);const [selected,setSelected]=useState(0);const [target,setTarget]=useState(0);const [message,setMessage]=useState('Sélectionnez le PNJ principal et sa cible.');const current=enemies[selected];const targetPlayer=players[target];
 const damage=(amount,label)=>{if(!current||current.hp<=0||!targetPlayer||targetPlayer.hp<=0)return;const d=Math.min(targetPlayer.hp,amount);setPlayers(t=>t.map((p,i)=>i===target?{...p,hp:Math.max(0,p.hp-d)}:p));setMessage(`${current.name} ${label} sur ${targetPlayer.name} : -${d} PV.`)};
 return <section className="battle-screen gm-battle"><header className="battle-topbar"><div><small>COMBAT · VUE MJ</small><h2>Gestion du combat</h2></div><div className="battle-mode gm"><b>MJ</b><span>vue inversée · PNJ principal</span></div><button onClick={onExit}>QUITTER</button></header><div className="gm-field"><div className="gm-column"><label>PNJ / ADVERSAIRES</label>{enemies.map((p,i)=><button key={p.name} className={i===selected?'gm-card selected':'gm-card'} onClick={()=>setSelected(i)}><span className="gm-icon">{p.icon}</span><div><b>{p.name}</b><small>Nv.{p.level} · {p.type}</small><Hp hp={p.hp} maxHp={p.maxHp}/><small>PV {p.hp}/{p.maxHp}</small></div></button>)}</div><div className="gm-versus">VS</div><div className="gm-column"><label>PERSONNAGES JOUEURS · CIBLES</label>{players.map((p,i)=><button key={p.name} className={i===target?'gm-card selected target':'gm-card'} onClick={()=>setTarget(i)}><span className="gm-icon">{p.icon}</span><div><b>{p.name}</b><small>Nv.{p.level} · {p.type}</small><Hp hp={p.hp} maxHp={p.maxHp}/><small>PV {p.hp}/{p.maxHp}</small></div></button>)}</div></div><div className="gm-command"><div><small>PNJ ACTIF</small><b>{current?.name}</b><small>CIBLE : {targetPlayer?.name}</small></div><button onClick={()=>damage(5,'attaque')}>ATTAQUER</button><button onClick={()=>damage(8,'utilise sa capacité')}>CAPACITÉ</button><button onClick={()=>{const next=enemies.findIndex((p,i)=>i!==selected&&p.hp>0);if(next>=0){setSelected(next);setMessage(`Le PNJ envoie ${enemies[next].name}.`)}}}>CHANGER</button><button onClick={()=>setMessage(`${current?.name} se défend.`)}>DÉFENDRE</button><p>{message}</p></div></section>
}
