import React,{useEffect,useMemo,useState}from'react';
import'./battle-real.css';
import{getHgssSpriteCandidates,spriteLabel}from'./hgssAssets.js';
const API='https://pokeapi.co/api/v2',POKEDEX_SIZE=1025;
const TYPE={normal:'NORMAL',fire:'FEU',water:'EAU',electric:'ÉLECTRIK',grass:'PLANTE',ice:'GLACE',fighting:'COMBAT',poison:'POISON',ground:'SOL',flying:'VOL',psychic:'PSY',bug:'INSECTE',rock:'ROCHE',ghost:'SPECTRE',dragon:'DRAGON',dark:'TÉNÈBRES',steel:'ACIER',fairy:'FÉE'};
const title=s=>String(s||'').split('-').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' '),typeName=t=>TYPE[t]||String(t||'').toUpperCase();
const maxHp=(level,base)=>Math.max(1,Math.floor(2*base*level/100)+level+10);
const sprite=(id,side='front')=>side==='back'?`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/${id}.png`:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/${id}.png`;
async function hydrate(ref,level=15){
 const r=await fetch(ref.url||`${API}/pokemon/${ref.id}`);if(!r.ok)throw Error('Pokémon introuvable');
 const d=await r.json(),stats={};for(const s of d.stats||[])stats[s.stat.name.replace('special-attack','specialAttack').replace('special-defense','specialDefense')]=s.base_stat;
 const vg=d.id<=493?'heartgold-soulsilver':'scarlet-violet';
 const learn=(d.moves||[]).flatMap(m=>m.version_group_details?.filter(v=>v.version_group.name===vg&&v.move_learn_method.name==='level-up'&&v.level_learned_at<=level).map(v=>({name:m.move.name,url:m.move.url,level:v.level_learned_at}))||[]).sort((a,b)=>a.level-b.level);
 const unique=[];for(const m of learn)if(!unique.some(x=>x.url===m.url))unique.push(m);const chosen=unique.slice(-4);
 const moves=(await Promise.all(chosen.map(async m=>{try{const x=await fetch(m.url).then(q=>q.json());return{name:title(x.name),power:x.power,accuracy:x.accuracy,pp:x.pp||1,type:x.type?.name||'normal',damageClass:x.damage_class?.name||'status',level:m.level}}catch{return null}}))).filter(Boolean);
 if(!moves.length)moves.push({name:'Charge',power:40,accuracy:100,pp:35,type:'normal',damageClass:'physical',level:1});
 const hp=maxHp(level,stats.hp||50);return{id:d.id,name:title(d.name),level,hp,maxHp:hp,stats,types:(d.types||[]).sort((a,b)=>a.slot-b.slot).map(x=>x.type.name),moves};
}
function Hp({hp,maxHp}){return <div className="hp hgss-hp"><i style={{width:`${Math.max(0,Math.min(100,hp/maxHp*100))}%`}}/></div>}
function Sprite({pokemon,side='front'}){const[i,setI]=useState(0),c=getHgssSpriteCandidates(pokemon,side),src=c[i];return <div className={`hgss-sprite ${side}`}>{src?<img src={src} alt={spriteLabel(pokemon.name,side)} onError={()=>setI(x=>x+1)}/>:<span>◉</span>}</div>}
function Fighter({pokemon,enemy}){return <div className={`fighter ${enemy?'enemy':'player'}`}><div className="hgss-status"><div className="status-line"><b>{pokemon.name}</b><strong>Lv{pokemon.level}</strong></div><div className="status-type">{pokemon.types.map(typeName).join(' / ')}</div><Hp hp={pokemon.hp} maxHp={pokemon.maxHp}/><small>HP {Math.max(0,pokemon.hp)}/{pokemon.maxHp}</small></div><Sprite pokemon={pokemon} side={enemy?'front':'back'}/></div>}
function Picker({label,selected,onSelect,excludeId}){const[list,setList]=useState([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true);useEffect(()=>{let dead=false;fetch(`${API}/pokemon?limit=${POKEDEX_SIZE}`).then(r=>r.json()).then(d=>{if(!dead)setList(d.results.map((x,i)=>({id:i+1,name:title(x.name),url:x.url})))}).finally(()=>!dead&&setLoading(false));return()=>{dead=true}},[]);const filtered=useMemo(()=>{const x=q.trim().toLowerCase();return list.filter(p=>p.id!==excludeId&&(!x||String(p.id)===x||p.name.toLowerCase().includes(x)))},[list,q,excludeId]);return <div className="pokemon-picker"><div className="pokemon-picker-title"><b>{label}</b><span>{list.length}/1025</span></div><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Rechercher par numéro ou nom…"/><div className="pokemon-picker-list">{loading?<small>Chargement du Pokédex national…</small>:filtered.map(p=><button type="button" key={p.id} className={selected?.id===p.id?'chosen':''} onClick={()=>onSelect(p)}><img src={sprite(p.id)} alt="" onError={e=>{e.currentTarget.src=`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png`}}/><strong>#{String(p.id).padStart(4,'0')}</strong><span>{p.name}</span></button>)}</div></div>}
function MovePanel({pokemon,onMove,busy}){return <div className="battle-subpanel hgss-moves"><div className="move-panel-title">CHOISISSEZ UNE ATTAQUE</div>{pokemon.moves.map((m,i)=><button className={`move-${m.type}`} key={`${m.name}-${i}`} disabled={busy||m.pp<=0||!m.power} onClick={()=>onMove(m)}><span className="move-type">{typeName(m.type)}</span><strong>{m.name}</strong><small>Puiss. {m.power||'—'} · Préc. {m.accuracy||'—'} · PP {m.pp}</small></button>)}</div>}
function CommandMenu({pokemon,onMove,busy,turn,panel,setPanel,setPicker}){return <div className="battle-command"><div className="command-main"><button className="command-fight" disabled={busy||turn!=='player'} onClick={()=>setPanel(panel==='moves'?null:'moves')}>⚔<span>COMBAT</span></button><button disabled={busy||turn!=='player'} onClick={()=>setPanel('bag')}>◒<span>SAC</span></button><button disabled={busy||turn!=='player'} onClick={()=>setPicker('player')}>●<span>POKÉMON</span></button><button disabled={busy||turn!=='player'} onClick={()=>setPanel('run')}>↪<span>FUITE</span></button>{panel==='moves'&&<MovePanel pokemon={pokemon} busy={busy} onMove={onMove}/>}</div><div className="command-party"><div className="party-ball">●</div><div><b>{pokemon.name}</b><small>Lv{pokemon.level}</small></div><div><Hp hp={pokemon.hp} maxHp={pokemon.maxHp}/><small>{pokemon.hp}/{pokemon.maxHp}</small></div></div></div>}
function MoveEffect({type}){return <div className={`move-effect effect-${type}`}><i/><i/><i/><i/></div>}
function damage(a,d,m){const atk=a.stats[m.damageClass==='special'?'specialAttack':'attack']||50,def=d.stats[m.damageClass==='special'?'specialDefense':'defense']||50,stab=a.types.includes(m.type)?1.5:1;return Math.max(1,Math.floor(((((2*a.level/5+2)*m.power*atk/def)/50)+2)*stab*(.85+Math.random()*.15)));}
export default function BattleViewReal({onExit}){const[player,setPlayer]=useState({id:25,name:'Pikachu',level:15,hp:55,maxHp:55,stats:{hp:55,attack:55,defense:40,specialAttack:50,specialDefense:50,speed:90},types:['electric'],moves:[{name:'Éclair',power:40,accuracy:100,pp:30,type:'electric',damageClass:'special'}]}),[enemy,setEnemy]=useState({id:1,name:'Bulbizarre',level:15,hp:45,maxHp:45,stats:{hp:45,attack:49,defense:49,specialAttack:65,specialDefense:65,speed:45},types:['grass','poison'],moves:[{name:'Charge',power:40,accuracy:100,pp:35,type:'normal',damageClass:'physical'}]}),[turn,setTurn]=useState('player'),[msg,setMsg]=useState('Que doit faire Pikachu ?'),[panel,setPanel]=useState(null),[picker,setPicker]=useState(null),[busy,setBusy]=useState(false),[effect,setEffect]=useState(null);
 const choose=async(kind,ref)=>{setBusy(true);try{const p=await hydrate(ref);kind==='player'?setPlayer(p):setEnemy(p);setMsg(kind==='player'?`Que doit faire ${p.name} ?`:`${p.name} apparaît !`);setPicker(null);setPanel(null);setTurn('player')}finally{setBusy(false)}};
 const move=m=>{if(busy||turn!=='player'||player.hp<=0||enemy.hp<=0)return;setPanel(null);setBusy(true);setEffect(m.type);const d=damage(player,enemy,m);setEnemy(x=>({...x,hp:Math.max(0,x.hp-d)}));setMsg(`${player.name} utilise ${m.name} !`);setTimeout(()=>setEffect(null),500);setTurn('enemy');setTimeout(()=>{if(enemy.hp-d<=0){setMsg(`${enemy.name} est K.O. !`);setBusy(false);setTurn('player');return}const em=enemy.moves[0],ed=damage(enemy,player,em);setEffect(em.type);setPlayer(x=>({...x,hp:Math.max(0,x.hp-ed)}));setMsg(`${enemy.name} utilise ${em.name} !`);setTimeout(()=>setEffect(null),500);setBusy(false);setTurn('player')},700)};
 return <section className="battle-screen hgss-battle"><header className="battle-topbar hgss-battle-top"><div><small>POKÉMON · COMBAT</small><h2>Combat</h2></div><div className="battle-mode"><b>HGSS</b><span>Pokédex national · 1 025</span></div><button onClick={onExit}>QUITTER</button></header>{picker&&<div className="battle-picker-overlay"><div className="battle-picker-modal"><button className="battle-picker-close" onClick={()=>setPicker(null)}>×</button><Picker label={picker==='player'?'POKÉMON ATTAQUANT':'POKÉMON DÉFENSIF'} selected={picker==='player'?player:enemy} excludeId={picker==='player'?enemy.id:player.id} onSelect={p=>choose(picker,p)}/></div></div>}<div className="battle-field hgss-field"><div className="hgss-battleback"/><div className="hgss-ground enemy-ground"/><div className="hgss-ground player-ground"/><Fighter pokemon={enemy} enemy/><Fighter pokemon={player}/>{effect&&<MoveEffect type={effect}/>}</div><div className="hgss-dialog"><b>{msg}</b><small>{busy?'':'À vous de jouer.'}</small></div><CommandMenu pokemon={player} onMove={move} busy={busy} turn={turn} panel={panel} setPanel={p=>{setPanel(p);if(p==='run')setMsg('Impossible de fuir ce combat de JDR.');if(p==='bag')setMsg('Le sac sera disponible dans le système d’objets.')}} setPicker={setPicker}/></section>}
export function GmBattleViewReal({onExit}){const[setup,setSetup]=useState(true),[attacker,setAttacker]=useState(null),[defender,setDefender]=useState(null),[players,setPlayers]=useState([]),[enemies,setEnemies]=useState([]),[msg,setMsg]=useState('Sélectionnez les deux Pokémon.');const launch=async()=>{if(!attacker||!defender)return;const[a,d]=await Promise.all([hydrate(attacker),hydrate(defender)]);setPlayers([a]);setEnemies([d]);setMsg(`${a.name} affronte ${d.name} !`);setSetup(false)};if(setup)return <section className="battle-screen gm-battle hgss-battle"><header className="battle-topbar hgss-battle-top"><div><small>COMBAT · INTERFACE MJ</small><h2>Préparer le combat</h2></div><div className="battle-mode gm"><b>MJ</b><span>Pokédex national · 1 025</span></div><button onClick={onExit}>QUITTER</button></header><div className="gm-setup hgss-setup"><div className="hgss-panel-title">CHOIX DES COMBATTANTS</div><div className="gm-picker-columns"><Picker label="ATTAQUANT / JOUEUR" selected={attacker} excludeId={defender?.id} onSelect={setAttacker}/><Picker label="DÉFENSEUR / PNJ" selected={defender} excludeId={attacker?.id} onSelect={setDefender}/></div><button className="gm-launch" disabled={!attacker||!defender} onClick={launch}>⚔ LANCER LE COMBAT</button></div></section>;const p=players[0],e=enemies[0];return <section className="battle-screen gm-battle hgss-battle"><header className="battle-topbar hgss-battle-top"><div><small>COMBAT · INTERFACE MJ</small><h2>Gestion du combat</h2></div><div className="battle-mode gm"><b>MJ</b><span>Combat réel · sprites HGSS</span></div><button onClick={onExit}>QUITTER</button></header><div className="gm-battle-stage"><div className="gm-stage-enemy"><span>DÉFENSEUR / PNJ</span>{e&&<><Sprite pokemon={e} side="front"/><h3>{e.name} · Lv{e.level}</h3><Hp hp={e.hp} maxHp={e.maxHp}/></>}</div><div className="gm-vs">VS</div><div className="gm-stage-player"><span>ATTAQUANT / JOUEUR</span>{p&&<><Sprite pokemon={p} side="back"/><h3>{p.name} · Lv{p.level}</h3><Hp hp={p.hp} maxHp={p.maxHp}/></>}</div></div><div className="gm-command hgss-gm-command"><div className="gm-target-list"><b>DÉFENSEUR</b><button className="selected" onClick={()=>setSetup(true)}>{e?.name||'—'}</button></div><div className="gm-target-list"><b>ATTAQUANT</b><button className="selected" onClick={()=>setSetup(true)}>{p?.name||'—'}</button></div><div className="gm-buttons"><button onClick={()=>{if(!p||!e)return;const m=p.moves[0],d=damage(p,e,m);setEnemies([{...e,hp:Math.max(0,e.hp-d)}]);setMsg(`${p.name} utilise ${m.name} : -${d} HP.`)}}>ATTAQUER</button><button onClick={()=>setMsg(`${p?.name} se défend.`)}>DÉFENDRE</button><button onClick={()=>setSetup(true)}>CHANGER DE POKÉMON</button></div><p>{msg}</p></div></section>}
