import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./style.css";
import{LOCATIONS}from"./world/locations.js";
const BASE=import.meta.env.BASE_URL||"/";
const ALL=LOCATIONS, KANTO=ALL.filter(x=>x.region==="Kanto"), JOHTO=ALL.filter(x=>x.region==="Johto"), find=name=>ALL.find(x=>x.name===name);
const POS={Johto:{"New Bark Town":[8,82],"Cherrygrove City":[20,73],"Violet City":[34,61],"Azalea Town":[39,75],"Goldenrod City":[51,58],"Ecruteak City":[64,50],"Olivine City":[49,38],"Cianwood City":[34,29],"Mahogany Town":[75,42],"Blackthorn City":[84,62],"Lake of Rage":[77,29],"Victory Road":[91,70],"Mt. Silver":[96,78],"Route 29":[13,78],"Route 30":[27,68],"Route 31":[32,62],"Route 32":[37,68],"Route 33":[39,78],"Route 34":[45,64],"Route 35":[54,52],"Route 36":[58,57],"Route 37":[61,51],"Route 38":[57,42],"Route 39":[52,42],"Route 40":[42,34],"Route 41":[36,30],"Route 42":[69,45],"Route 43":[75,35],"Route 44":[79,52],"Route 45":[83,68],"Route 46":[19,84],"Route 47":[30,86],"Route 48":[38,86]},Kanto:{"Indigo Plateau":[7,48],"Pallet Town":[13,67],"Viridian City":[22,59],"Pewter City":[29,43],"Cerulean City":[53,29],"Saffron City":[55,48],"Celadon City":[43,51],"Lavender Town":[70,52],"Vermilion City":[54,65],"Fuchsia City":[70,76],"Cinnabar Island":[55,91],"Route 1":[18,63],"Route 2":[25,51],"Route 3":[41,35],"Route 4":[48,29],"Route 5":[55,38],"Route 6":[55,57],"Route 7":[49,50],"Route 8":[62,50],"Route 9":[62,35],"Route 10":[67,42],"Route 11":[63,68],"Route 12":[70,61],"Route 13":[74,69],"Route 14":[73,74],"Route 15":[70,76],"Route 16":[35,55],"Route 17":[51,72],"Route 18":[68,78],"Route 20":[54,86],"Route 21":[47,83],"Route 22":[14,58],"Route 24":[55,23],"Route 25":[62,20]}};
function position(l){return POS[l.region]?.[l.name]||[50,50]}
function edges(items){const by=new Map(ALL.map(x=>[x.name,x])),out=[],seen=new Set();for(const a of items)for(const n of a.connections||[]){const b=by.get(n);if(!b)continue;const k=[a.name,b.name].sort().join("|");if(!seen.has(k)){seen.add(k);out.push([a,b])}}return out}
function Header({mode,setMode,search,setSearch,onEditor}){return <header className="topbar"><div className="brand"><div className="ball"><i/></div><div><b>POKÉMON JDR</b><small>MONDE HGSS · MJ / JOUEUR</small></div></div><div className="actions"><input value={search}onChange={e=>setSearch(e.target.value)}placeholder="Ville, route, lieu…"/><button onClick={onEditor}>ÉDITEUR</button><button className={mode==="player"?"active":""}onClick={()=>setMode("player")}>JOUEUR</button><button className={mode==="gm"?"active gm":""}onClick={()=>setMode("gm")}>MJ</button></div></header>}
function GlobalMap({items,selected,setSelected,region}){const es=useMemo(()=>edges(items),[items]);return <div className="global-map"><div className="terrain-label">{region.toUpperCase()} · CARTE GLOBALE</div><svg viewBox="0 0 100 100" preserveAspectRatio="none">{es.map(([a,b],i)=>{const p=position(a),q=position(b);return <line key={i}x1={p[0]}y1={p[1]}x2={q[0]}y2={q[1]}/>})}</svg>{items.map(l=>{const p=position(l);return <button key={l.id}className={`world-node ${l.type} ${selected?.id===l.id?"selected":""}`}style={{left:p[0]+"%",top:p[1]+"%"}}onClick={()=>setSelected(l)}><strong>{l.type==="city"?"●":"◆"}</strong><span>{l.name}</span></button>})}</div>}
function SideLists({items,selected,setSelected}){return <aside className="sidebar">{["city","route","landmark"].map(type=>{const a=items.filter(x=>x.type===type);return <section className="list-card"key={type}><header><b>{type==="city"?"VILLES":type==="route"?"ROUTES":"LIEUX"}</b><span>{a.length}</span></header><div>{a.map(l=><button key={l.id}className={selected?.id===l.id?"chosen":""}onClick={()=>setSelected(l)}><i className={`dot ${l.type}`}/><strong>{l.name}</strong><small>{l.npcCount} PNJ · event {l.eventIndex}</small></button>)}</div></section>})}</aside>}
function Detail({location,setSelected}){if(!location)return <section className="detail empty">Sélectionnez un lieu.</section>;return <section className="detail"><small>{location.region} · {location.type}</small><h1>{location.name}</h1><div className="stats"><b>{location.npcCount}<small>PNJ / événements</small></b><b>{location.eventIndex}<small>event index</small></b><b>{(location.connections||[]).length}<small>connexions</small></b></div><h3>Connexions</h3><div className="connections">{(location.connections||[]).map(n=>find(n)).filter(Boolean).map(t=><button key={t.id}onClick={()=>setSelected(t)}>{t.name}<small>{t.region}</small></button>)}</div></section>}
function Npcs({location}){const n=location?.npcCount||0;return <section className="npc-panel"><header><b>PNJ / ÉVÉNEMENTS OVERWORLD</b><span>{n}</span></header><div className="npc-grid">{Array.from({length:n},(_,i)=><button key={i}><b>PNJ {String(i+1).padStart(2,"0")}</b><small>Overworld</small></button>)}</div></section>}
function loadModelViewer(){if(document.querySelector("script[data-hgss-model-viewer]"))return;const s=document.createElement("script");s.type="module";s.dataset.hgssModelViewer="1";s.src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js";document.head.appendChild(s)}
function PlayMap({location,setLocation}){const[px,setPx]=useState(50),[py,setPy]=useState(50),[ready,setReady]=useState(false);useEffect(()=>{loadModelViewer();setTimeout(()=>setReady(true),300)},[]);useEffect(()=>{const f=e=>{let x=px,y=py;if(e.key==="ArrowUp"||e.key.toLowerCase()==="z")y-=1;if(e.key==="ArrowDown"||e.key.toLowerCase()==="s")y+=1;if(e.key==="ArrowLeft"||e.key.toLowerCase()==="q")x-=1;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")x+=1;if(x!==px||y!==py){e.preventDefault();setPx(Math.max(5,Math.min(95,x)));setPy(Math.max(5,Math.min(95,y)))}};window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[px,py]);const id=location?.name==="Route 29"?30:location?.name==="New Bark Town"?57:null;const src=id?`${BASE}assets/hgss/generated/maps/${id}/rendered/nsbmd.glb`:null;const near=(location?.connections||[]).map(find).filter(Boolean);return <section className="play-screen"><div className="play-hud"><b>{location?.name||"OVERWORLD"}</b><span>HGSS · MODÈLE RÉEL</span><span>Position {px},{py}</span></div><div className="game-viewport hgss-viewport">{ready&&src?<model-viewer src={src}camera-controls disable-pan shadow-intensity="0.4" camera-orbit="0deg 72deg auto" field-of-view="28deg" interaction-prompt="none" style={{width:"100%",height:"100%",background:"#6b765f"}}/>:<div className="missing-map"><b>CARTE HGSS</b><p>{id?`Map ${id} extraite.`:"Sélectionnez Route 29 ou New Bark Town."}</p><small>Après extraction : convertissez le NSBMD en GLB avec <code>tools/hgss/convert_models.py</code>.</small></div>}<div className="player-overlay"style={{left:`${px}%`,top:`${py}%`}}>●</div></div><div className="play-bottom"><div><b>↑ ↓ ← → / ZQSD</b><small>Caméra et position du joueur conservées</small></div><div className="route-select">{near.slice(0,4).map(n=><button key={n.id}onClick={()=>setLocation(n)}>{n.name}</button>)}</div></div></section>}
function TileEditor({open,onClose}){if(!open)return null;return <div className="modal-backdrop"><section className="modal editor"><header><div><small>ÉDITEUR</small><h2>Éditeur HGSS</h2></div><button onClick={onClose}>×</button></header><p>Les cartes réelles sont maintenant alimentées par les données extraites de la ROM. L'édition de terrain sera branchée sur PER/BDHC après le renderer.</p></section></div>}
function App(){const[mode,setMode]=useState("player"),[region,setRegion]=useState("Johto"),[search,setSearch]=useState(""),[selected,setSelected]=useState(find("New Bark Town")),[location,setLocation]=useState(find("New Bark Town")),[editor,setEditor]=useState(false);const items=useMemo(()=>ALL.filter(x=>x.region===region&&x.name.toLowerCase().includes(search.toLowerCase())),[region,search]);const fallback=(region==="Kanto"?KANTO:JOHTO)[0]||ALL[0];const loc=location?.region===region?location:fallback;return <><Header mode={mode}setMode={setMode}search={search}setSearch={setSearch}onEditor={()=>setEditor(true)}/><div className="region-bar"><button className={region==="Johto"?"sel":""}onClick={()=>setRegion("Johto")}>JOHTO · {JOHTO.length} lieux</button><button className={region==="Kanto"?"sel":""}onClick={()=>setRegion("Kanto")}>KANTO · {KANTO.length} lieux</button></div><main className="layout"><SideLists items={items}selected={selected}setSelected={l=>{setSelected(l);setLocation(l)}}/><section className="workspace"><div className="hero"><div><small>{mode==="gm"?"MJ · VUE DÉTAILLÉE":"JOUEUR · OVERWORLD"}</small><h2>{region} · carte interactive</h2></div><div className="counters"><span>{items.filter(x=>x.type==="city").length} villes</span><span>{items.filter(x=>x.type==="route").length} routes</span></div></div>{mode==="gm"?<><GlobalMap items={items}selected={selected}setSelected={l=>{setSelected(l);setLocation(l)}}region={region}/><div className="bottom"><Detail location={selected}setSelected={l=>{setSelected(l);setLocation(l)}}/><Npcs location={selected}/></div></>:<PlayMap location={loc}setLocation={l=>{setLocation(l);setSelected(l)}}/>}</section></main><footer className="global-footer">HGSS · renderer basé sur les données de maps extraites · joueur / MJ</footer><TileEditor open={editor}onClose={()=>setEditor(false)}/></>}
createRoot(document.getElementById("root")).render(<App/>);
