import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./style.css";
import{LOCATIONS}from"./world/locations.js";
const ALL=LOCATIONS,KANTO=ALL.filter(x=>x.region==="Kanto"),JOHTO=ALL.filter(x=>x.region==="Johto");
function Header({mode,setMode,setSearch}){return <header className="topbar"><div className="brand"><div className="ball"><i/></div><div><b>POKÉMON JDR</b><small>ATLAS · JOHTO + KANTO · HGSS</small></div></div><div className="actions"><input placeholder="Rechercher une ville, route, lieu…" onChange={e=>setSearch(e.target.value)}/><button className={mode==="player"?"active":""}onClick={()=>setMode("player")}>JOUEUR</button><button className={mode==="gm"?"active gm":""}onClick={()=>setMode("gm")}>MJ</button></div></header>}
function RegionTabs({region,setRegion}){return <div className="tabs"><button className={region==="Johto"?"sel":""}onClick={()=>setRegion("Johto")}>JOHTO <small>{JOHTO.length} lieux</small></button><button className={region==="Kanto"?"sel":""}onClick={()=>setRegion("Kanto")}>KANTO <small>{KANTO.length} lieux</small></button></div>}
function Atlas({locations,selected,setSelected}){const visible=locations.filter(x=>x.position);const edges=useMemo(()=>{const map=new Map(ALL.map(x=>[x.name,x])),out=[];for(const a of visible)for(const n of a.connections||[]){const b=map.get(n);if(b?.position){const key=[a.name,b.name].sort().join("|");if(!out.some(e=>e.key===key))out.push({key,a,b})}}return out},[visible]);return <div className="atlas"><div className="atlas-grid"/><svg viewBox="0 0 120 105" preserveAspectRatio="none" className="roads">{edges.map(e=><line key={e.key}x1={e.a.position[0]}y1={e.a.position[1]}x2={e.b.position[0]}y2={e.b.position[1]}/>)}</svg>{visible.map(l=><button key={l.id} className={`node ${l.type} ${selected?.id===l.id?"selected":""}`} style={{left:`${l.position[0]}%`,top:`${l.position[1]}%`}} onClick={()=>setSelected(l)}><span>{l.type==="city"?"●":"◆"}</span><b>{l.name}</b>{l.npcCount>0&&<small>{l.npcCount} PNJ</small>}</button>)}</div>}
function LocationList({items,selected,setSelected,title}){return <section className="list-card"><header><b>{title}</b><span>{items.length}</span></header><div>{items.map(l=><button key={l.id}className={selected?.id===l.id?"chosen":""}onClick={()=>setSelected(l)}><span className={`dot ${l.type}`}/><strong>{l.name}</strong><small>{l.npcCount} PNJ · event {l.eventIndex}</small></button>)}</div></section>}
function NpcPanel({location,mode}){const count=location?.npcCount||0;const rows=Array.from({length:count},(_,i)=>({id:i+1,label:`PNJ ${String(i+1).padStart(2,"0")}`,role:["Dresseur","Habitant","Voyageur","Commerçant","Personnage"][i%5]}));return <section className="npc-panel"><header><div><small>ÉVÉNEMENTS OVERWORLD</small><h2>{location?.name||"Sélectionnez un lieu"}</h2></div>{location&&<span>{count} PNJ</span>}</header>{!location?<div className="empty">Sélectionnez une ville ou une route pour afficher ses événements.</div>:<><div className="meta"><span>{location.region}</span><span>EVENT {location.eventIndex}</span><span>{location.type.toUpperCase()}</span></div><div className="npc-grid">{rows.map(n=><button key={n.id}className="npc"onClick={()=>mode==="gm"&&alert(`${n.label} · ${n.role}\nLieu : ${location.name}\nIndex événement : ${location.eventIndex}`)}><i>👤</i><b>{n.label}</b><small>{n.role}</small></button>)}</div>{mode==="gm"&&<footer>Mode MJ : les PNJ sont prêts à recevoir leurs fiches, scripts et dialogues sans dépendre du renderer de carte.</footer>}</>}</section>}
function Detail({location,setSelected}){if(!location)return <div className="detail empty">Sélectionnez un lieu dans l’atlas.</div>;const targets=(location.connections||[]).map(n=>ALL.find(x=>x.name===n)).filter(Boolean);return <div className="detail"><div className="detail-head"><div><small>{location.region} · {location.type}</small><h1>{location.name}</h1></div><button onClick={()=>setSelected(null)}>×</button></div><div className="stats"><div><b>{location.npcCount}</b><small>PNJ / événements</small></div><div><b>{location.eventIndex}</b><small>index événement</small></div><div><b>{location.connections?.length||0}</b><small>connexions</small></div></div><h3>Connexions</h3><div className="connections">{targets.length?targets.map(t=><button key={t.id}onClick={()=>setSelected(t)}>{t.name}<small>{t.type}</small></button>):<span>Aucune connexion cartographiée dans cette vue.</span>}</div><div className="source-note">Les routes, villes, lieux et index d’événements proviennent de la structure HGSS extraite du document fourni. Le nouveau système est indépendant de l’ancien renderer de tiles arbitraires.</div></div>}
function App(){const[mode,setMode]=useState("player"),[region,setRegion]=useState("Johto"),[search,setSearch]=useState(""),[selected,setSelected]=useState(ALL.find(x=>x.name==="New Bark Town"));const filtered=useMemo(()=>ALL.filter(x=>x.region===region&&x.name.toLowerCase().includes(search.toLowerCase())),[region,search]);const routes=filtered.filter(x=>x.type==="route"),cities=filtered.filter(x=>x.type==="city"),landmarks=filtered.filter(x=>x.type==="landmark");return <><Header mode={mode}setMode={setMode}setSearch={setSearch}/><main><aside className="sidebar"><RegionTabs region={region}setRegion={setRegion}/><LocationList items={cities}selected={selected}setSelected={setSelected}title="Villes / bourgs"/><LocationList items={routes}selected={selected}setSelected={setSelected}title="Routes"/><LocationList items={landmarks}selected={selected}setSelected={setSelected}title="Lieux remarquables"/></aside><section className="workspace"><div className="hero"><div><small>ATLAS INTERACTIF</small><h2>{region} · HeartGold / SoulSilver</h2></div><div className="counters"><span>{cities.length} villes</span><span>{routes.length} routes</span><span>{filtered.reduce((n,x)=>n+x.npcCount,0)} PNJ</span></div></div><Atlas locations={filtered}selected={selected}setSelected={setSelected}/><div className="bottom"><Detail location={selected}setSelected={setSelected}/><NpcPanel location={selected}mode={mode}/></div></section></main><footer className="global-footer">Pokémon JDR · monde refondu · {ALL.length} lieux référencés · {ALL.reduce((n,x)=>n+x.npcCount,0)} événements overworld référencés</footer></>}
createRoot(document.getElementById("root")).render(<App/>);
