import React,{useEffect,useRef,useState}from'react';
import'./hgss-map.css';
import*as THREE from'three';
import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';

const BASE=(import.meta.env.BASE_URL||'/').replace(/\/$/,'');
const CELL=100,GRID_W=47,GRID_H=17;
const MAP_IDS={'Route 29':30,'New Bark Town':57};
const mapIdFromName=name=>MAP_IDS[name]??null;
const findCell=(matrix,id)=>{const r=(matrix?.nonZero||[]).find(([x,y,m])=>Number(m)===Number(id));return r?{x:Number(r[0]),y:Number(r[1]),id:Number(r[2])}:null};
function disposeObject(root){root.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose())}})}

export default function HGSSViewport({name='Route 29',connections=[],onChange}){
 const host=useRef(null),cameraRef=useRef(null),rendererRef=useRef(null),worldRef=useRef(null),frameRef=useRef(null),objectsRef=useRef(new Map()),matrixRef=useRef(null),drag=useRef(null);
 const[matrix,setMatrix]=useState(null),[status,setStatus]=useState('Chargement de la matrice HGSS…'),[zoom,setZoom]=useState(.28),[loaded,setLoaded]=useState(0),[follow,setFollow]=useState(false),[blocked,setBlocked]=useState(null),[permissions,setPermissions]=useState({});
 const[player,setPlayer]=useState({mapId:30,x:16,y:16});
 useEffect(()=>{let dead=false;fetch(`${BASE}/assets/hgss/johto-matrix.json`).then(r=>r.json()).then(m=>{if(dead)return;matrixRef.current=m;setMatrix(m);const id=mapIdFromName(name);const c=findCell(m,id)||findCell(m,30)||{x:0,y:0,id:30};setPlayer({mapId:c.id,x:16,y:16})}).catch(()=>setStatus('Impossible de charger la matrice HGSS.'));return()=>{dead=true}},[name]);
 useEffect(()=>{if(!host.current)return;const el=host.current,scene=new THREE.Scene();scene.background=null;const camera=new THREE.OrthographicCamera(-900,900,520,-520,1,10000);camera.position.set(GRID_W*CELL/2,2200,GRID_H*CELL/2);camera.lookAt(GRID_W*CELL/2,0,GRID_H*CELL/2);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;el.innerHTML='';el.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x65705b,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(700,1800,900);scene.add(sun);const world=new THREE.Group();scene.add(world);cameraRef.current=camera;rendererRef.current=renderer;worldRef.current=world;const resize=()=>{const w=el.clientWidth||900,h=el.clientHeight||520,a=w/h,half=700/zoom;renderer.setSize(w,h,false);camera.left=-half*a;camera.right=half*a;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix()};const wheel=e=>{e.preventDefault();setZoom(z=>Math.max(.22,Math.min(2.2,+(z+(e.deltaY<0?.08:-.08)).toFixed(2))))};const down=e=>{drag.current={x:e.clientX,y:e.clientY,cx:camera.position.x,cz:camera.position.z}};const move=e=>{if(!drag.current)return;const s=1/zoom;camera.position.x=drag.current.cx-(e.clientX-drag.current.x)*s*1.7;camera.position.z=drag.current.cz-(e.clientY-drag.current.y)*s*1.7;camera.updateProjectionMatrix()};const up=()=>{drag.current=null};el.addEventListener('wheel',wheel,{passive:false});el.addEventListener('pointerdown',down);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('resize',resize);resize();const animate=()=>{frameRef.current=requestAnimationFrame(animate);renderer.render(scene,camera)};animate();return()=>{cancelAnimationFrame(frameRef.current);el.removeEventListener('wheel',wheel);el.removeEventListener('pointerdown',down);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('resize',resize);objectsRef.current.forEach(disposeObject);objectsRef.current.clear();renderer.dispose();el.innerHTML=''}},[]);
 useEffect(()=>{const renderer=rendererRef.current,camera=cameraRef.current,el=host.current;if(!renderer||!camera||!el)return;const w=el.clientWidth||900,h=el.clientHeight||520,a=w/h,half=700/zoom;camera.left=-half*a;camera.right=half*a;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix()},[zoom]);
 useEffect(()=>{if(!matrix||!worldRef.current)return;const world=worldRef.current,loader=new GLTFLoader(),ids=[...new Set((matrix.nonZero||[]).map(r=>Number(r[2])))].filter(Number.isFinite);let cancelled=false,count=0;setLoaded(0);setStatus(`Rendus HGSS : 0 / ${ids.length}`);ids.forEach(id=>{const existing=[...objectsRef.current.keys()].some(k=>String(k).startsWith(`${id}:`));if(existing){count++;setLoaded(count);return}loader.load(`${BASE}/assets/hgss/generated/maps/${id}/rendered/nsbmd.glb`,gltf=>{if(cancelled)return;const root=gltf.scene,box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=CELL*.96/Math.max(size.x,size.z,1);root.scale.setScalar(scale);root.position.x-=center.x*scale;root.position.z-=center.z*scale;root.position.y-=box.min.y*scale;(matrix.nonZero||[]).filter(r=>Number(r[2])===id).forEach(([gx,gy])=>{const instance=root.clone(true);instance.position.x=Number(gx)*CELL+CELL/2;instance.position.z=Number(gy)*CELL+CELL/2;world.add(instance);objectsRef.current.set(`${id}:${gx}:${gy}`,instance)});count++;setLoaded(count);setStatus(count===ids.length?'Carte Johto HGSS assemblée depuis les maps de la ROM.':`Rendus HGSS : ${count} / ${ids.length}`)},undefined,()=>{count++;setLoaded(count);setStatus(`Rendus HGSS : ${count} / ${ids.length} · rendu manquant pour ${id}`)})});return()=>{cancelled=true}},[matrix]);
 useEffect(()=>{const id=player.mapId;if(!id||permissions[id])return;let dead=false;fetch(`${BASE}/assets/hgss/generated/maps/${id}/permissions.json`).then(r=>r.ok?r.json():null).then(p=>{if(!dead&&p)setPermissions(x=>({...x,[id]:p}))}).catch(()=>{});return()=>{dead=true}},[player.mapId,permissions]);
 useEffect(()=>{if(!follow||!matrix)return;const camera=cameraRef.current,cell=findCell(matrix,player.mapId);if(!camera||!cell)return;camera.position.x=cell.x*CELL+(player.x/32)*CELL;camera.position.z=cell.y*CELL+(player.y/32)*CELL;camera.updateProjectionMatrix()},[player,follow,matrix]);
 const isBlocked=(id,x,y)=>!!permissions[id]?.cells?.find(c=>c.x===x&&c.y===y)?.blocked;
 const move=dir=>{const dx=dir==='left'?-1:dir==='right'?1:0,dy=dir==='up'?-1:dir==='down'?1:0;setPlayer(p=>{let x=p.x+dx,y=p.y+dy,id=p.mapId;if(x>=0&&x<32&&y>=0&&y<32){if(isBlocked(id,x,y)){setBlocked('Case bloquée par les collisions HGSS');return p}setBlocked(null);return{...p,x,y}}if(!matrix)return p;const c=findCell(matrix,id);if(!c)return p;const nx=c.x+(x<0?-1:x>=32?1:0),ny=c.y+(y<0?-1:y>=32?1:0),target=(matrix.nonZero||[]).find(r=>Number(r[0])===nx&&Number(r[1])===ny);if(!target){setBlocked('Zone inaccessible : aucun rendu HGSS à cet endroit');return p}const tx=x<0?31:x>=32?0:x,ty=y<0?31:y>=32?0:y,tid=Number(target[2]);if(isBlocked(tid,tx,ty)){setBlocked('Passage bloqué par les collisions HGSS');return p}const next=connections.find(v=>mapIdFromName(v.name)===tid);if(next)onChange?.(next);setBlocked(null);return{mapId:tid,x:tx,y:ty}})};
 useEffect(()=>{const key=e=>{if(['INPUT','TEXTAREA','BUTTON'].includes(e.target?.tagName))return;const k=e.key.toLowerCase(),d=k==='arrowup'||k==='z'||k==='w'?'up':k==='arrowdown'||k==='s'?'down':k==='arrowleft'||k==='q'||k==='a'?'left':k==='arrowright'||k==='d'?'right':null;if(d){e.preventDefault();move(d)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[permissions,connections,matrix]);
 const pc=(matrix?.nonZero||[]).find(r=>Number(r[2])===Number(player.mapId));const left=pc?((Number(pc[0])+player.x/32)/GRID_W)*100:50,top=pc?((Number(pc[1])+player.y/32)/GRID_H)*100:50;
 const fullMap=()=>{setFollow(false);setZoom(.28);if(cameraRef.current&&matrix){cameraRef.current.position.set(GRID_W*CELL/2,2200,GRID_H*CELL/2);cameraRef.current.lookAt(GRID_W*CELL/2,0,GRID_H*CELL/2);cameraRef.current.updateProjectionMatrix()}};
 const followPlayer=()=>{setFollow(true);setZoom(.62)};
 return <section className="hgss-play"><div className="hgss-head"><div><b>{name}</b><span>OVERWORLD HGSS · assemblage des rendus réels de la ROM</span></div><div className="hgss-map-status">{status}</div></div><div className="hgss-canvas-wrap"><div className="hgss-real-map-stage"><div ref={host} className="hgss-gl-map"/><div className="hgss-map-grid-label">47 × 17 cellules · trous = zones absentes / inaccessibles</div><div className="hgss-player" style={{left:`${left}%`,top:`${top}%`}}><span/></div><div className="hgss-controls"><button type="button" onClick={fullMap}>Carte entière</button><button type="button" onClick={followPlayer}>Suivre le joueur</button><span>↑ ↓ ← → · ZQSD/WASD</span><b>{loaded} rendus</b></div><div className="hgss-map-label"><b>{name}</b><span>Map {player.mapId} · case {player.x},{player.y} · {Math.round(zoom*100)}%</span>{blocked&&<em>{blocked}</em>}</div></div></div><div className="hgss-nav">{connections.map(c=><button key={c.id} type="button" onClick={()=>onChange?.(c)}>→ {c.name}</button>)}</div></section>;
}
