import React,{useEffect,useMemo,useState}from'react';
import'./johto-starter-map.css';
const POKE='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon';
const TRAINER='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/trainers';
const N={fr:{'New Bark Town':'Bourg Geon','Route 29':'Route 29','Cherrygrove City':'Ville Griotte',Elm:'Prof. Orme',Mom:'Maman',Youngster:'Gamin',BugCatcher:'Scout',Guide:'Guide de la ville',wild:'Pokémon sauvage',start:'DÉPLACEMENT : FLÈCHES / ZQSD',battle:'COMBATTRE',talk:'PARLER',close:'FERMER'},en:{'New Bark Town':'New Bark Town','Route 29':'Route 29','Cherrygrove City':'Cherrygrove City',Elm:'Professor Elm',Mom:'Mom',Youngster:'Youngster',BugCatcher:'Bug Catcher',Guide:'City Guide',wild:'Wild Pokémon',start:'MOVE : ARROWS / WASD',battle:'BATTLE',talk:'TALK',close:'CLOSE'}};
const MAPS={
 'New Bark Town':{w:32,h:20,spawn:[15,16],grass:[[5,5],[6,5],[7,5],[8,5],[5,6],[6,6],[7,6],[8,6]],houses:[[5,3],[21,3],[13,2]],water:[[26,1],[27,1],[28,1],[29,1],[26,2],[27,2],[28,2],[29,2],[26,3],[27,3],[28,3],[29,3]],npcs:[{key:'Elm',x:14,y:5,sprite:'scientist',dialog:{fr:'Bonjour ! Je suis le Prof. Orme. Bienvenue à Bourg Geon.',en:'Hello! I am Professor Elm. Welcome to New Bark Town.'},team:[{id:152,name:{fr:'Germignon',en:'Chikorita'},level:5}]},{key:'Mom',x:23,y:7,sprite:'lass',dialog:{fr:'Fais attention sur la Route 29 !',en:'Be careful on Route 29!'},team:[]}]},
 'Route 29':{w:48,h:26,spawn:[3,23],grass:[[9,5],[10,5],[11,5],[12,5],[13,5],[14,5],[9,6],[10,6],[11,6],[12,6],[13,6],[14,6],[29,16],[30,16],[31,16],[32,16],[33,16],[34,16],[29,17],[30,17],[31,17],[32,17],[33,17],[34,17]],water:[[41,5],[42,5],[43,5],[41,6],[42,6],[43,6],[41,7],[42,7],[43,7]],npcs:[{key:'Youngster',x:19,y:10,sprite:'youngster',dialog:{fr:'Hé ! Toi là ! Viens te battre !',en:'Hey! You! Come battle me!'},team:[{id:19,name:{fr:'Rattata',en:'Rattata'},level:4}]},{key:'BugCatcher',x:35,y:12,sprite:'bug-catcher',dialog:{fr:'Mes Pokémon Insecte sont prêts !',en:'My Bug Pokémon are ready!'},team:[{id:10,name:{fr:'Chenipan',en:'Caterpie'},level:3},{id:13,name:{fr:'Aspicot',en:'Weedle'},level:3}]}],connections:{west:'Cherrygrove City',east:'New Bark Town'}},
 'Cherrygrove City':{w:34,h:22,spawn:[5,17],grass:[[24,5],[25,5],[26,5],[27,5],[24,6],[25,6],[26,6],[27,6]],houses:[[5,3],[19,3],[5,12],[20,12]],water:[[27,1],[28,1],[29,1],[30,1],[27,2],[28,2],[29,2],[30,2]],npcs:[{key:'Guide',x:15,y:9,sprite:'youngster',dialog:{fr:'Bienvenue à Ville Griotte !',en:'Welcome to Cherrygrove City!'},team:[]}]}
};
const WILD=[{id:16,name:{fr:'Roucool',en:'Pidgey'},level:3},{id:19,name:{fr:'Rattata',en:'Rattata'},level:3},{id:161,name:{fr:'Fouinette',en:'Sentret'},level:4}];
const key=(x,y)=>`${x},${y}`;
export default function JohtoStarterMap({location='Route 29',lang='fr',onBattle,onChange}){
 const t=N[lang]||N.fr,d=MAPS[location]||MAPS['Route 29'];const[pos,setPos]=useState(()=>({x:d.spawn[0],y:d.spawn[1]}));const[dir,setDir]=useState('down'),[moving,setMoving]=useState(false),[dialog,setDialog]=useState(null),[zoom,setZoom]=useState(1);
 useEffect(()=>{setPos({x:d.spawn[0],y:d.spawn[1]});setDialog(null)},[location,d.spawn]);
 const sets=useMemo(()=>({grass:new Set((d.grass||[]).map(p=>key(...p))),water:new Set((d.water||[]).map(p=>key(...p))),houses:new Set((d.houses||[]).flatMap(([x,y])=>[key(x,y),key(x+1,y),key(x,y+1),key(x+1,y+1)]))}),[d]);
 const npcs=d.npcs||[];const npcAt=(x,y)=>npcs.find(n=>n.x===x&&n.y===y);const blocked=(x,y)=>x<0||y<0||x>=d.w||y>=d.h||sets.water.has(key(x,y))||sets.houses.has(key(x,y))||npcs.some(n=>n.x===x&&n.y===y);
 const move=(dx,dy)=>{setDir(dx>0?'right':dx<0?'left':dy>0?'down':'up');setMoving(true);setTimeout(()=>setMoving(false),130);setPos(p=>{const nx=p.x+dx,ny=p.y+dy;if(blocked(nx,ny))return p;const npc=npcAt(nx,ny);if(npc){setDialog({npc,action:'talk'});return p}if(sets.grass.has(key(nx,ny))&&Math.random()<0.14){const w=WILD[Math.floor(Math.random()*WILD.length)];setDialog({wild:w});return{x:nx,y:ny}}if(nx===d.w-1&&location==='New Bark Town'){onChange?.('Route 29');return p}if(nx===0&&location==='Cherrygrove City'){onChange?.('Route 29');return p}return{x:nx,y:ny}})};
 useEffect(()=>{const h=e=>{if(dialog)return;const k=e.key.toLowerCase();if(['arrowup','w'].includes(k)){e.preventDefault();move(0,-1)}else if(['arrowdown','s'].includes(k)){e.preventDefault();move(0,1)}else if(['arrowleft','a','q'].includes(k)){e.preventDefault();move(-1,0)}else if(['arrowright','d'].includes(k)){e.preventDefault();move(1,0)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[dialog,location]);
 const startBattle=(payload)=>{setDialog(null);onBattle?.({name:payload.npc?payload.npc.key:payload.wild?.name?.[lang],level:payload.npc?.team?.[0]?.level||payload.wild?.level||3,id:payload.wild?.id||payload.npc?.team?.[0]?.id||19,capturable:!!payload.wild,enemyTeam:payload.npc?.team||[payload.wild]})};
 const tiles=[];for(let y=0;y<d.h;y++)for(let x=0;x<d.w;x++){let type='ground';if(sets.water.has(key(x,y)))type='water';else if(sets.houses.has(key(x,y)))type='house';else if(sets.grass.has(key(x,y)))type='grass';else if(y<2||x<2||x>d.w-3||y>d.h-3)type='tree';tiles.push(<div className={`world-tile ${type}`} key={key(x,y)}/>)}
 return <section className="starter-map playable-world"><header className="starter-map-header"><div><small>{t.start}</small><h2>{t[location]||location}</h2></div><div className="map-toolbar"><button type="button" onClick={()=>setZoom(z=>Math.max(.75,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button type="button" onClick={()=>setZoom(z=>Math.min(1.5,z+.1))}>+</button></div></header><nav className="map-location-tabs">{Object.keys(MAPS).map(n=><button type="button" key={n} className={n===location?'active':''} onClick={()=>onChange?.(n)}>{t[n]||n}</button>)}</nav><div className="world-viewport"><div className="world-map" style={{width:d.w*32,height:d.h*32,transform:`scale(${zoom})`,transformOrigin:'top left'}}>{tiles}{(d.houses||[]).map(([x,y],i)=><div className="world-house" key={`h${i}`} style={{left:x*32,top:y*32}}>⌂</div>)}{npcs.map((n,i)=><button type="button" className="world-npc-sprite" key={i} style={{left:n.x*32,top:n.y*32}} onClick={()=>setDialog({npc:n,action:'talk'})}><img src={`${TRAINER}/${n.sprite}.png`} alt="" onError={e=>{e.currentTarget.src=`${TRAINER}/red.png`}}/><span>{t[n.key]}</span></button>)}<div className="player-sprite ${dir} ${moving?'walking':''}" style={{left:pos.x*32,top:pos.y*32}}><img src={`${TRAINER}/red.png`} alt="Joueur" onError={e=>{e.currentTarget.style.display='none'}}/></div></div></div><div className="map-controls"><button type="button" onClick={()=>move(0,-1)}>▲</button><button type="button" onClick={()=>move(-1,0)}>◀</button><button type="button" onClick={()=>move(1,0)}>▶</button><button type="button" onClick={()=>move(0,1)}>▼</button></div>{dialog&&<div className="world-dialog-overlay"><div className="world-dialog"><div className="dialog-name">{dialog.npc?t[dialog.npc.key]:t.wild}</div>{dialog.npc?<><p>{dialog.npc.dialog[lang]}</p>{dialog.npc.team?.length>0&&<div className="enemy-preview">{dialog.npc.team.map((p,i)=><div key={i}><img src={`${POKE}/${p.id}.png`} alt=""/><b>{p.name[lang]}</b><span>Nv. {p.level}</span></div>)}</div>}<div className="dialog-buttons"><button type="button" onClick={()=>startBattle(dialog)}>{t.battle}</button><button type="button" onClick={()=>setDialog(null)}>{t.close}</button></div></>:<><p>{lang==='fr'?`Un ${dialog.wild.name.fr} sauvage vous bloque le passage !`:`A wild ${dialog.wild.name.en} is blocking your way!`}</p><div className="enemy-preview"><div><img src={`${POKE}/${dialog.wild.id}.png`} alt=""/><b>{dialog.wild.name[lang]}</b><span>Nv. {dialog.wild.level}</span></div></div><div className="dialog-buttons"><button type="button" onClick={()=>startBattle(dialog)}>{t.battle}</button><button type="button" onClick={()=>setDialog(null)}>{t.close}</button></div></>}</div></div>}</section>;
}