import React,{useEffect,useMemo,useState,useCallback}from'react';
import'./johto-starter-map.css';
const POKE='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon';
const TRAINER='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/trainers';
const MAP_ASSETS={
 'New Bark Town':'https://archives.bulbagarden.net/wiki/Special:Redirect/file/New_Bark_Town_HGSS.png',
 'Route 29':'https://www.pokemontrash.com/images/heartgold-soulsilver/cartes/route-29-partie-1.png',
 'Cherrygrove City':'https://archives.bulbagarden.net/wiki/Special:Redirect/file/Cherrygrove_City_HGSS.png'
};
const N={fr:{'New Bark Town':'Bourg Geon','Route 29':'Route 29','Cherrygrove City':'Ville Griotte',Elm:'Prof. Orme',Mom:'Maman',Youngster:'Gamin',BugCatcher:'Scout',Guide:'Guide de la ville',wild:'Pokémon sauvage',start:'DÉPLACEMENT : FLÈCHES / ZQSD',battle:'COMBATTRE',talk:'PARLER',close:'FERMER'},en:{'New Bark Town':'New Bark Town','Route 29':'Route 29','Cherrygrove City':'Cherrygrove City',Elm:'Professor Elm',Mom:'Mom',Youngster:'Youngster',BugCatcher:'Bug Catcher',Guide:'City Guide',wild:'Wild Pokémon',start:'MOVE : ARROWS / WASD',battle:'BATTLE',talk:'TALK',close:'CLOSE'}};
const MAPS={
 'New Bark Town':{w:32,h:20,tile:32,spawn:[15,16],grass:[[5,5],[6,5],[7,5],[8,5],[5,6],[6,6],[7,6],[8,6]],houses:[[5,3],[21,3],[13,2]],water:[[26,1],[27,1],[28,1],[29,1],[26,2],[27,2],[28,2],[29,2],[26,3],[27,3],[28,3],[29,3]],npcs:[{key:'Elm',x:14,y:5,sprite:'scientist',dialog:{fr:'Bonjour ! Je suis le Prof. Orme. Bienvenue à Bourg Geon.',en:'Hello! I am Professor Elm. Welcome to New Bark Town.'},team:[{id:152,name:{fr:'Germignon',en:'Chikorita'},level:5}]},{key:'Mom',x:23,y:7,sprite:'lass',dialog:{fr:'Fais attention sur la Route 29 !',en:'Be careful on Route 29!'},team:[]}],visibleWild:[]},
 'Route 29':{w:48,h:17,tile:33,spawn:[3,15],grass:[[8,6],[9,6],[10,6],[11,6],[12,6],[13,6],[14,6],[8,7],[9,7],[10,7],[11,7],[12,7],[13,7],[14,7],[30,10],[31,10],[32,10],[33,10],[34,10],[35,10],[30,11],[31,11],[32,11],[33,11],[34,11],[35,11]],water:[[41,3],[42,3],[43,3],[41,4],[42,4],[43,4],[41,5],[42,5],[43,5]],npcs:[{key:'Youngster',x:20,y:8,sprite:'youngster',dialog:{fr:'Hé ! Toi là ! Viens te battre !',en:'Hey! You! Come battle me!'},team:[{id:19,name:{fr:'Rattata',en:'Rattata'},level:4}]},{key:'BugCatcher',x:37,y:9,sprite:'bug-catcher',dialog:{fr:'Mes Pokémon Insecte sont prêts !',en:'My Bug Pokémon are ready!'},team:[{id:10,name:{fr:'Chenipan',en:'Caterpie'},level:3},{id:13,name:{fr:'Aspicot',en:'Weedle'},level:3}]}],visibleWild:[{x:11,y:6,wild:{id:16,name:{fr:'Roucool',en:'Pidgey'},level:3}},{x:33,y:10,wild:{id:19,name:{fr:'Rattata',en:'Rattata'},level:3}}]},
 'Cherrygrove City':{w:34,h:22,tile:32,spawn:[5,17],grass:[[24,5],[25,5],[26,5],[27,5],[24,6],[25,6],[26,6],[27,6]],houses:[[5,3],[19,3],[5,12],[20,12]],water:[[27,1],[28,1],[29,1],[30,1],[27,2],[28,2],[29,2],[30,2]],npcs:[{key:'Guide',x:15,y:9,sprite:'youngster',dialog:{fr:'Bienvenue à Ville Griotte !',en:'Welcome to Cherrygrove City!'},team:[]}],visibleWild:[]}
};
const WILD=[{id:16,name:{fr:'Roucool',en:'Pidgey'},level:3},{id:19,name:{fr:'Rattata',en:'Rattata'},level:3},{id:161,name:{fr:'Fouinette',en:'Sentret'},level:4}];
const key=(x,y)=>`${x},${y}`;
export default function JohtoStarterMap({location='Route 29',lang='fr',onBattle,onChange}){
 const t=N[lang]||N.fr,d=MAPS[location]||MAPS['Route 29'];
 const[pos,setPos]=useState(()=>({x:d.spawn[0],y:d.spawn[1]}));
 const[dir,setDir]=useState('down'),[moving,setMoving]=useState(false),[dialog,setDialog]=useState(null),[zoom,setZoom]=useState(1);
 useEffect(()=>{setPos({x:d.spawn[0],y:d.spawn[1]});setDialog(null)},[location,d.spawn]);
 const sets=useMemo(()=>({grass:new Set((d.grass||[]).map(p=>key(...p))),water:new Set((d.water||[]).map(p=>key(...p))),houses:new Set((d.houses||[]).flatMap(([x,y])=>[key(x,y),key(x+1,y),key(x,y+1),key(x+1,y+1)]))}),[d]);
 const npcs=d.npcs||[];const npcAt=(x,y)=>npcs.find(n=>n.x===x&&n.y===y);const blocked=(x,y)=>x<0||y<0||x>=d.w||y>=d.h||sets.water.has(key(x,y))||sets.houses.has(key(x,y))||npcs.some(n=>n.x===x&&n.y===y);
 const move=useCallback((dx,dy)=>{if(dialog)return;setDir(dx>0?'right':dx<0?'left':dy>0?'down':'up');setMoving(true);window.setTimeout(()=>setMoving(false),130);setPos(p=>{const nx=p.x+dx,ny=p.y+dy;if(blocked(nx,ny))return p;const npc=npcAt(nx,ny);if(npc){setDialog({npc,action:'talk'});return p}if(sets.grass.has(key(nx,ny))&&Math.random()<0.14){const w=WILD[Math.floor(Math.random()*WILD.length)];setDialog({wild:w});return{x:nx,y:ny}}if(location==='New Bark Town'&&nx>=d.w-1){onChange?.('Route 29');return p}if(location==='Route 29'&&nx>=d.w-1){onChange?.('Cherrygrove City');return p}if(location==='Cherrygrove City'&&nx<=0){onChange?.('Route 29');return p}return{x:nx,y:ny}})},[dialog,blocked,npcAt,sets,location,d.w,onChange]);
 useEffect(()=>{const h=e=>{const k=e.key.toLowerCase();if(['arrowup','w','z'].includes(k)){e.preventDefault();move(0,-1)}else if(['arrowdown','s'].includes(k)){e.preventDefault();move(0,1)}else if(['arrowleft','a','q'].includes(k)){e.preventDefault();move(-1,0)}else if(['arrowright','d'].includes(k)){e.preventDefault();move(1,0)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[move]);
 const startBattle=payload=>{setDialog(null);onBattle?.({name:payload.npc?payload.npc.key:payload.wild?.name?.[lang],level:payload.npc?.team?.[0]?.level||payload.wild?.level||3,id:payload.wild?.id||payload.npc?.team?.[0]?.id||19,capturable:!!payload.wild,enemyTeam:payload.npc?.team||[payload.wild]})};
 const worldWidth=d.w*d.tile,worldHeight=d.h*d.tile;
 const playerLeft=pos.x*d.tile,playerTop=pos.y*d.tile;
 return <section className="starter-map playable-world"><header className="starter-map-header"><div><small>{t.start}</small><h2>{t[location]||location}</h2></div><div className="map-toolbar"><button type="button" onClick={()=>setZoom(z=>Math.max(.75,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button type="button" onClick={()=>setZoom(z=>Math.min(1.5,z+.1))}>+</button></div></header><nav className="map-location-tabs">{Object.keys(MAPS).map(n=><button type="button" key={n} className={n===location?'active':''} onClick={()=>onChange?.(n)}>{t[n]||n}</button>)}</nav><div className="world-viewport"><div className="world-map" style={{width:worldWidth,height:worldHeight,transform:`scale(${zoom})`,backgroundImage:`url(${MAP_ASSETS[location]})`}}>{npcs.map((n,i)=><button type="button" className="world-npc-sprite" key={i} style={{left:n.x*d.tile,top:n.y*d.tile}} onClick={()=>setDialog({npc:n,action:'talk'})}><img src={`${TRAINER}/${n.sprite}.png`} alt="" onError={e=>{e.currentTarget.src=`${TRAINER}/red.png`}}/><span>{t[n.key]}</span></button>)}{(d.visibleWild||[]).map((v,i)=><button type="button" className="world-wild-sprite" key={`wild-${i}`} style={{left:v.x*d.tile,top:v.y*d.tile}} onClick={()=>setDialog({wild:v.wild})}><img src={`${POKE}/${v.wild.id}.png`} alt={v.wild.name[lang]}/><span>{v.wild.name[lang]} · Nv.{v.wild.level}</span></button>)}<div className={`player-sprite ${dir} ${moving?'walking':''}`} style={{left:playerLeft,top:playerTop}}><img src={`${TRAINER}/red.png`} alt="Joueur"/></div></div></div><div className="map-controls"><button type="button" onClick={()=>move(0,-1)}>▲</button><button type="button" onClick={()=>move(-1,0)}>◀</button><button type="button" onClick={()=>move(1,0)}>▶</button><button type="button" onClick={()=>move(0,1)}>▼</button></div>{dialog&&<div className="world-dialog-overlay"><div className="world-dialog"><div className="dialog-name">{dialog.npc?t[dialog.npc.key]:t.wild}</div>{dialog.npc?<><p>{dialog.npc.dialog[lang]}</p>{dialog.npc.team?.length>0&&<div className="enemy-preview">{dialog.npc.team.map((p,i)=><div key={i}><img src={`${POKE}/${p.id}.png`} alt=""/><b>{p.name[lang]}</b><span>Nv. {p.level}</span></div>)}</div>}<div className="dialog-buttons"><button type="button" onClick={()=>startBattle(dialog)}>{t.battle}</button><button type="button" onClick={()=>setDialog(null)}>{t.close}</button></div></>:<><p>{lang==='fr'?`Un ${dialog.wild.name.fr} sauvage vous bloque le passage !`:`A wild ${dialog.wild.name.en} is blocking your way!`}</p><div className="enemy-preview"><div><img src={`${POKE}/${dialog.wild.id}.png`} alt=""/><b>{dialog.wild.name[lang]}</b><span>Nv. {dialog.wild.level}</span></div></div><div className="dialog-buttons"><button type="button" onClick={()=>startBattle(dialog)}>{t.battle}</button><button type="button" onClick={()=>setDialog(null)}>{t.close}</button></div></>}</div></div>}</section>;
}