import * as THREE from 'three';

const WORDS={0x14:1,0x15:0,0x16:1,0x17:1,0x18:1,0x19:0,0x1a:16,0x1b:12,0x1c:16,0x1d:12,0x1e:9,0x1f:3,0x20:1,0x21:1,0x22:1,0x23:2,0x24:1,0x25:1,0x26:1,0x27:1,0x28:1,0x29:1,0x2a:1,0x2b:1,0x40:1,0x41:0};
const u16=(d,o)=>d.getUint16(o,true), s16=(d,o)=>d.getInt16(o,true), u32=(d,o)=>d.getUint32(o,true), fx=v=>v/4096;
function ascii(d,o){let s='';for(let i=0;i<16&&o+i<d.byteLength;i++){const c=d.getUint8(o+i);if(!c)break;s+=String.fromCharCode(c)}return s}
function dict(d,o){if(o<0||o+16>d.byteLength)return null;const n=d.getUint8(o+1),vs=o+16+n*4;if(vs+n*4>d.byteLength)return null;const values=[];for(let i=0;i<n;i++)values.push(u32(d,vs+i*4));return{values,names:Array.from({length:n},(_,i)=>ascii(d,vs+n*4+i*16))}}
function locate(d){let bmd=-1;for(let i=0;i<Math.min(d.byteLength,0x100)-4;i++)if(ascii(d,i)==='BMD0'){bmd=i;break}if(bmd<0)throw Error('BMD0 introuvable');const blocks=u16(d,bmd+14);let mdl=-1;for(let i=0;i<blocks;i++){const o=bmd+u32(d,bmd+16+i*4);if(ascii(d,o)==='MDL0'){mdl=o;break}}if(mdl<0)throw Error('MDL0 introuvable');const md=dict(d,mdl+8);if(!md?.values.length)throw Error('Dictionnaire MDL0 invalide');const model=mdl+md.values[0],ml=model+u32(d,model+12),meshes=dict(d,ml);if(!meshes)throw Error('MeshList invalide');return{ml,meshes}}
const s10=v=>{v&=1023;return v&512?v-1024:v};
function decode(d,base,index){if(base+16>d.byteLength)return null;const start=base+u32(d,base+8),end=Math.min(d.byteLength,start+u32(d,base+12));if(start+4>end)return null;const verts=[],faces=[];let prim=-1,last=[0,0,0],pending=[],p=start;const emit=v=>{const i=verts.length;verts.push(...v);if(prim===0){pending.push(i/3);if(pending.length>=3)faces.push(pending.slice(-3))}else if(prim===1){pending.push(i/3);if(pending.length>=4){const n=pending.length;faces.push([pending[n-4],pending[n-3],pending[n-2]],[pending[n-4],pending[n-2],pending[n-1]])}}last=v};
while(p+4<=end){const packet=u32(d,p);p+=4;for(let slot=0;slot<4;slot++){const op=(packet>>>(slot*8))&255;if(!op)continue;if(op===64){if(p+4>end)return null;prim=u32(d,p)&3;p+=4;pending=[];continue}if(op===65){prim=-1;pending=[];continue}const w=WORDS[op];if(w==null||p+w*4>end){p=end;break}if(op===35)emit([fx(s16(d,p)),fx(s16(d,p+2)),fx(s16(d,p+4))]);else if(op===36){const x=s10(u32(d,p)),y=s10(u32(d,p)>>>10),z=s10(u32(d,p)>>>20);emit([fx(x<<3),fx(y<<3),fx(z<<3)])}else if(op===40){const q=u32(d,p);emit([last[0]+fx(s10(q)<<3),last[1]+fx(s10(q>>>10)<<3),last[2]+fx(s10(q>>>20)<<3)])}else if(op===37)emit([fx(s16(d,p)),fx(s16(d,p+2)),last[2]]);else if(op===38)emit([fx(s16(d,p)),last[1],fx(s16(d,p+2))]);else if(op===39)emit([last[0],fx(s16(d,p)),fx(s16(d,p+2))]);p+=w*4}}if(!faces.length)return null;const pos=[];for(const f of faces)for(const i of f)pos.push(verts[i*3],verts[i*3+1],verts[i*3+2]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.computeVertexNormals();const m=new THREE.MeshLambertMaterial({color:0x8eaa72,flatShading:true,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,m);mesh.name=`NSBMD mesh ${index}`;return mesh}
export async function loadNSBMD(url){const r=await fetch(url);if(!r.ok)throw Error(`NSBMD HTTP ${r.status}`);const d=new DataView(await r.arrayBuffer()),{ml,meshes}=locate(d),group=new THREE.Group();meshes.values.forEach((rel,i)=>{const mesh=decode(d,ml+rel,i);if(mesh)group.add(mesh)});if(!group.children.length)throw Error('Aucune géométrie exploitable dans le NSBMD');group.rotation.x=-Math.PI/2;return group}
